Add support for edge reconnection
eclipse-sirius/sirius-web pull request #1204
Opened 2022-05-09 09:40 UTC by gcoutable

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [x] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [x] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [x] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [x] Variables have a proper type
- [x] Functions’ arguments have a proper type
- [x] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2022-09-20 15:08 UTC, gcoutable commented
This PR is ready for review but since it needs both #997 and #931 to work, I keep this PR in draft.

2022-10-10 10:06 UTC, sbegaudeau requested changes
I haven't finish the review but here's a first comment.

2022-10-10 10:06 UTC, sbegaudeau commented on packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/description/DiagramDescription.java
> +    }
The `DiagramDescription` is not to be used as a delivery boy anymore than it is already. If you need to ask for a reconnection tool in the `ViewReconnectionToolsExecutor` then you should figure it out there. Don't add this data structure here only as a shortcut for the View DSL support.

2022-10-10 12:19 UTC, pcdavid commented on CHANGELOG.adoc
> +- https://github.com/eclipse-sirius/sirius-components/issues/780[#780] [diagram] Add support for edge reconnection. Edge reconnection descriptions can be defined either inside a classical Sirius desk
Typos:
- "you can defined" => "you can define"
- "need to defined" => "need to define"

2022-10-10 12:19 UTC, pcdavid commented on doc/adrs/074_add_support_for_edge_reconnection.adoc
> +input ReconnectEdgeInput {
This does not match what is actually in `diagram.graphqls`:

```
enum ReconnectEdgeKind {
  SOURCE
  TARGET
}

input ReconnectEdgeInput {
  id: ID!
  editingContextId: ID!
  representationId: ID!
  edgeId: String!
  newEdgeEndId: String!
  reconnectEdgeKind: ReconnectEdgeKind!
  newEdgeEndPosition: PositionInput!
}
```

2022-10-10 12:19 UTC, pcdavid commented on doc/adrs/074_add_support_for_edge_reconnection.adoc
> +We will have to adapte the reconnect action to take account of the source and target anchor relative position ratio.
Typo: "adapte" => "adapt"

2022-10-10 12:19 UTC, pcdavid commented on doc/adrs/074_add_support_for_edge_reconnection.adoc
> +When the end is dropped, Sprotty tries to find the right node to reconnect the edge. Unfortunately Sprotty select the most distant ancestor on which the edge end is dropped while we wanted the elemen
- "Sprotty select" => "Sprotty selects"
- "we wanted" => "we want"
- missing line breaks between sentences

2022-10-10 12:19 UTC, pcdavid commented on doc/adrs/074_add_support_for_edge_reconnection.adoc
> +
These are all very low-level technical/implementation details, but it's not clear how the overall feature works from the end-user's point of view:
- how does the visual feeback (if any) look like during a reconnect?
- how does the user know if the current mouse position is a valid reconnection end?
- what if the user tries to reconnect an edge that does _not_ have a reconnection tool?
- when reconnecting an edge which has multiple bendpoints, how are they affected? is the edge "straightened" and all bendpoints removed (below you say "reconnecting an edge is similar to removing an edge, then creating a new one", which would behave like that), or are the existing bendpoints preserved and only the first/segment modified?

2022-10-17 15:38 UTC, sbegaudeau approved these changes

2022-10-17 15:38 UTC, merged