Add support for a "Rich Text" widget in forms
eclipse-sirius/sirius-web pull request #1384
Opened 2022-10-03 07:34 UTC by pcdavid

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2022-10-10 15:43 UTC, AxelRICHARD requested changes

2022-10-10 15:43 UTC, AxelRICHARD commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx
> +          </div>{' '}
Why this {' '} ?

2022-10-10 15:43 UTC, AxelRICHARD commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/RichTextWidget.tsx
> +    color: '#000',
Are you sure about this color value ?

2022-10-10 15:43 UTC, AxelRICHARD commented on packages/view/backend/sirius-components-view-edit/plugin.properties
> +# Copyright (c) 2021, 2022 Obeo.
Why this plugin.properties file is only committed now?

2022-10-18 07:42 UTC, pcdavid commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx
> +          </div>{' '}
Done.

2022-10-18 07:48 UTC, pcdavid commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/RichTextWidget.tsx
> +    color: '#000',
The black `color`? What's the issue with it?

2022-10-18 08:55 UTC, AxelRICHARD commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/RichTextWidget.tsx
> +    color: '#000',
None, I just wanted to be sure that you want to put here a specific color, that do not comes from the sirius color theme.

2022-10-19 13:27 UTC, pcdavid commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/RichTextWidget.tsx
> +    color: '#000',
Fixed to use `theme.palette.text.primary`.

2022-11-07 10:28 UTC, AxelRICHARD requested changes

2022-11-07 10:28 UTC, AxelRICHARD commented on packages/forms/backend/sirius-components-forms/src/main/java/org/eclipse/sirius/components/forms/components/RichTextComponentProps.java
> + * Copyright (c) 2020 Obeo.
2020 -> 2022

2022-11-07 10:28 UTC, AxelRICHARD commented on packages/forms/frontend/sirius-components-forms/src/richtexteditor/RichTextEditor.tsx
> +          placeholder={<div className={classes.editorPlaceholder}>{placeholder}</div>}
The placeholder has been put in a weird position, under text text area:
<img width="283" alt="Capture d’écran 2022-11-07 à 10 35 26" src="https://user-images.githubusercontent.com/717752/200278031-da8d1e01-46f5-4593-8607-4a1762753a1e.png">
Is it possible to put on the text area?

2022-11-07 11:08 UTC, AxelRICHARD requested changes

2022-11-07 11:08 UTC, AxelRICHARD commented on packages/view/backend/sirius-components-view-edit/src/main/java/org/eclipse/sirius/components/view/provider/ViewItemProviderAdapterFactory.java
> +    /**
Please add new RichTextDescription in org.eclipse.sirius.components.view.provider.FormDescriptionItemProvider.collectNewChildDescriptors(Collection<Object>, Object)

2022-11-21 15:33 UTC, AxelRICHARD approved these changes

2022-11-21 15:52 UTC, merged