[1439] Handle ToolbarActions in Form/FormDescriptionEditor
eclipse-sirius/sirius-web pull request #1464
Opened 2022-11-14 15:15 UTC by AxelRICHARD

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [x] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [x] Have the relevant issues been added to the same project and milestone as the pull request?
- [x] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [x] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [x] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [x] Does the title of the commit contributing the ADR start with `[doc]`?
- [x] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [x] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [x] Variables have a proper type
- [x] Functions’ arguments have a proper type
- [x] Functions’ return type are specified
- Hooks are properly typed:
	- [x] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [x] `useState<STATE_TYPE>(…)`
- [x] All components have a proper typing for their props
- [x] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [x] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2022-11-18 13:51 UTC, pcdavid requested changes

2022-11-18 13:51 UTC, pcdavid commented on doc/adrs/077_add_support_for_toolbar_actions_in_form_and_formdescriptioneditor.adoc
> +In the FormDescriptionEditor, It will be possible to add new ToolbarActions from a dedicated '+' button located at the end of the toolbar.
Typos: "It" => "it"

2022-11-18 13:51 UTC, pcdavid commented on doc/adrs/077_add_support_for_toolbar_actions_in_form_and_formdescriptioneditor.adoc
> +  - new contained multi-valued reference : `toolbarActions` with type `ButtonDescription`.
This does not display properly as a list.

2022-11-18 13:51 UTC, pcdavid commented on packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/resources/schema/formdescriptioneditor.graphqls
> +  toolbarActions: [FormDescriptionEditorToolbarAction!]!
Can't we reuse the generic `AbstractFormDescriptionEditorWidget`? They are structurally identical.

2022-11-18 13:51 UTC, pcdavid commented on packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/MoveToolbarActionEventHandler.java
> +                    }
Catch `IndexOutOfBoundsException` to prevent "crashing" the event handler?
I think it *is* possible to get an invalid index here without it being a bug, for example if Alice and Bob are both editing the same FormDescription, Alice requests the deletion of a widget, and before the deletion is executed and Bob's client is refreshed, Bob sends a request to move a widget to an index which will no longer be valid after Alice's event has been treated.

2022-11-18 13:51 UTC, pcdavid commented on packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/AddToolbarActionEventHandlerTests.java
> +        assertThat(payload).isInstanceOf(AddToolbarActionSuccessPayload.class);
This does not actually test that the handler has added the action.

```
@@ -44,10 +45,11 @@
 public class AddToolbarActionEventHandlerTests {
     @Test
     public void testAddToolbarAction() {
+        FormDescription formDescription = ViewFactory.eINSTANCE.createFormDescription();
         var objectService = new IObjectService.NoOp() {
             @Override
             public Optional<Object> getObject(IEditingContext editingContext, String objectId) {
-                return Optional.of(ViewFactory.eINSTANCE.createFormDescription());
+                return Optional.of(formDescription);
             }
         };
         var handler = new AddToolbarActionEventHandler(objectService, new ICollaborativeFormDescriptionEditorMessageService.NoOp(), new SimpleMeterRegistry());
@@ -66,5 +68,6 @@
 
         IPayload payload = payloadSink.asMono().block();
         assertThat(payload).isInstanceOf(AddToolbarActionSuccessPayload.class);
+        assertThat(formDescription.getToolbarActions()).hasSize(1);
     }
 }
```

2022-11-18 13:51 UTC, pcdavid commented on packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/DeleteToolbarActionEventHandlerTests.java
> +        handler.handle(payloadSink, changeDescriptionSink, new IEditingContext.NoOp(), formDescriptionEditorContext, input);
Not sure what this really tests given that the overridden `deleteToolbarAction` does nothing.

2022-11-18 15:38 UTC, AxelRICHARD commented on packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/DeleteToolbarActionEventHandlerTests.java
> +        handler.handle(payloadSink, changeDescriptionSink, new IEditingContext.NoOp(), formDescriptionEditorContext, input);
Done

2022-11-18 15:38 UTC, AxelRICHARD commented on packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/test/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/AddToolbarActionEventHandlerTests.java
> +        assertThat(payload).isInstanceOf(AddToolbarActionSuccessPayload.class);
Done

2022-11-18 15:38 UTC, AxelRICHARD commented on packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/java/org/eclipse/sirius/components/collaborative/formdescriptioneditors/handlers/MoveToolbarActionEventHandler.java
> +                    }
Done

2022-11-18 15:38 UTC, AxelRICHARD commented on doc/adrs/077_add_support_for_toolbar_actions_in_form_and_formdescriptioneditor.adoc
> +  - new contained multi-valued reference : `toolbarActions` with type `ButtonDescription`.
Done

2022-11-18 15:39 UTC, AxelRICHARD commented on doc/adrs/077_add_support_for_toolbar_actions_in_form_and_formdescriptioneditor.adoc
> +In the FormDescriptionEditor, It will be possible to add new ToolbarActions from a dedicated '+' button located at the end of the toolbar.
Done

2022-11-18 15:41 UTC, AxelRICHARD commented on packages/formdescriptioneditors/backend/sirius-components-collaborative-formdescriptioneditors/src/main/resources/schema/formdescriptioneditor.graphqls
> +  toolbarActions: [FormDescriptionEditorToolbarAction!]!
Yes but it allows to easily distinguish toolbar actions from others widgets in `FormDescriptionEditorElementFactory#instantiateForm`

2022-11-21 09:56 UTC, pcdavid approved these changes

2022-11-21 10:25 UTC, merged