[1614] Add a SuccessPayload to replace most basic payloads
eclipse-sirius/sirius-web pull request #1659
Opened 2023-02-02 13:46 UTC by mcharfadi

Bug: #1614
Signed-off-by: Michaël Charfadi <michael.charfadi@obeosoft.com>

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2023-02-02 14:06 UTC, gcoutable requested changes, later dismissed

2023-02-02 14:06 UTC, gcoutable commented on packages/diagrams/frontend/sirius-components-diagrams/src/representation/operations.ts
> +      ... on SuccessPayload {
What about `EditLabelSuccessPayload` and some other success payloads in this file? 
We do not use this payload specifically, not like `InvokeSingleClickOnDiagramElementToolSuccessPayload`.

2023-02-02 14:06 UTC, gcoutable commented on packages/diagrams/frontend/sirius-components-diagrams/src/representation/operations.ts
> +      ... on SuccessPayload {
You may need to look for all the `**SuccessPayload` in this file and look if they cannot be transformed into `SuccessPayload` (or maybe simply removed from there).

2023-02-02 14:07 UTC, AxelRICHARD commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx
> +const isErrorPayload = (payload: GQLSuccessPayload): payload is GQLErrorPayload =>
Are you sure about this? It seems strange that a GQLSuccessPayload could be a GQLErrorPayload.

2023-02-02 14:07 UTC, AxelRICHARD commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/Group.tsx
> +const isErrorPayload = (payload: GQLSuccessPayload): payload is GQLErrorPayload =>
Are you sure about this? It seems strange that a GQLSuccessPayload could be a GQLErrorPayload.

2023-02-02 14:07 UTC, AxelRICHARD commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActionWidget.tsx
> +const isErrorPayload = (payload: GQLSuccessPayload): payload is GQLErrorPayload =>
Are you sure about this? It seems strange that a GQLSuccessPayload could be a GQLErrorPayload.

2023-02-02 14:07 UTC, AxelRICHARD commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActions.tsx
> +const isErrorPayload = (payload: GQLSuccessPayload): payload is GQLErrorPayload =>
Are you sure about this? It seems strange that a GQLSuccessPayload could be a GQLErrorPayload.

2023-02-02 14:07 UTC, AxelRICHARD commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetEntry.tsx
> +const isErrorPayload = (payload: GQLSuccessPayload): payload is GQLErrorPayload =>
Are you sure about this? It seems strange that a GQLSuccessPayload could be a GQLErrorPayload.

2023-02-02 14:07 UTC, AxelRICHARD commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorEventFragment.types.ts
> +export interface GQLErrorPayload
Are you sure about this? Shouldn't it be the opposite?

2023-02-02 14:21 UTC, sbegaudeau requested changes

2023-02-02 14:21 UTC, sbegaudeau commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FlexboxContainerWidget.tsx
> +const isErrorPayload = (payload: GQLSuccessPayload): payload is GQLErrorPayload =>
This cannot be true, ever

2023-02-02 14:21 UTC, sbegaudeau commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorEventFragment.types.ts
> +export interface GQLErrorPayload
How so?

2023-02-02 14:21 UTC, sbegaudeau commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx
> +const isErrorPayload = (payload: GQLSuccessPayload): payload is GQLErrorPayload =>
It can never be true

2023-02-03 18:14 UTC, sbegaudeau commented
There is still an outdated reference to `GQLAddWidgetSuccessPayload` among the 926 references to a `XxxSuccessPayload` in the code. I'll handle it and update the pull request accordingly.

Please also ensure that your commit messages are properly formatted with the full URL of the bug after `Bug:`. I'll raise an issue to perform this kind of check automatically.

2023-02-03 18:17 UTC, sbegaudeau commented
I still have some manual tests to perform before merging this PR

2023-02-03 19:45 UTC, sbegaudeau approved these changes

2023-02-03 19:46 UTC, merged