[1922] Flow migration
eclipse-sirius/sirius-web pull request #1939
Opened 2023-04-19 08:37 UTC by mcharfadi

Bug: https://github.com/eclipse-sirius/sirius-components/issues/1922

2023-04-25 08:44 UTC, mbats commented on doc/iterations/YYYY-MM/2023.6/shapes/shape Migration flow.adoc
> += (appetite) Shape
Give a name and an appetite to the shape

2023-04-25 08:44 UTC, mbats commented on doc/iterations/YYYY-MM/2023.6/shapes/shape Migration flow.adoc
> +In order to show that the view DSL can support everything the compatibility layer support, we should migrate flow to the view DSL. Using a dedicated package named flow, we should add a new project si
In order to include a test which covers the all odesign to view migration path, we will migrate the existing flow model.

2023-04-25 08:44 UTC, mbats commented on doc/iterations/YYYY-MM/2023.6/shapes/shape Migration flow.adoc
> +Use the the soon to be introduced Java APIs to create view models. https://github.com/eclipse-sirius/sirius-components/issues/1919
Use the the -> Use the

2023-04-25 08:44 UTC, mbats commented on doc/iterations/YYYY-MM/2023.6/shapes/shape Migration flow.adoc
> +Giving a flow model defined in a odesign file, we should be able to generate a view model witch match all concepts in the odesign model.
witch -> which
match all concepts -> match all the concepts existing in the odesign flow model

2023-04-25 08:44 UTC, mbats commented on doc/iterations/YYYY-MM/2023.6/shapes/shape Migration flow.adoc
> +=== Breadboarding
No UI involved

2023-04-26 14:46 UTC, sbegaudeau requested changes

2023-04-26 14:46 UTC, sbegaudeau commented on doc/iterations/2023.6/scopes/scope Migration flow.adoc
> +- [ ] Integrated tests updated
As mentionned in your other shape pull request, do not contribute the scope now. It is to be maintained in your branch where you will work on the feature and contributed when it's over.
Same comment regarding the title of the commit / pull request

2023-04-26 14:46 UTC, sbegaudeau commented on doc/iterations/2023.6/shapes/shape Migration flow.adoc
> +This view model should be generated using the soon to be introduced Java APIs to create view models. https://github.com/eclipse-sirius/sirius-components/issues/1919
You need to specify clearly the order of the various tasks that you will perform during this iteration. It's not clear for me yet and there are multiple possible solutions.

2023-04-26 14:46 UTC, sbegaudeau commented on doc/iterations/2023.6/shapes/shape Migration flow.adoc
> +The flow odesign model should be converted to a view model. All concepts used in the flow model should have a respective view concept.
One sentence per file

2023-04-26 14:46 UTC, sbegaudeau commented on doc/iterations/2023.6/shapes/shape Migration flow.adoc
> +Use the soon to be introduced Java APIs to create view models. https://github.com/eclipse-sirius/sirius-components/issues/1919
- Where will this file be located? in which project? In which Git repository? https://github.com/ObeoNetwork/FlowDesigner like the existing flow.odesign file? How can I reuse it in other applications using flow already?
- Will it depend on existing flow projects to retrieve the meta-model? (I think so)
- Will it depend on existing flow projects to retrieve existing Java services? (I don't think so)

2023-04-26 14:46 UTC, sbegaudeau commented on doc/iterations/2023.6/shapes/shape Migration flow.adoc
> +Giving a flow model defined in a odesign file, we should be able to generate a view model which  match all the concepts existing in the odesign flow model
The end user will not do that, the end user will open Sirius Web and not see and single change at all. Everything will work as before. including our Cypress integration tests which are heavily relying on flow.

2023-04-27 15:15 UTC, closed without merging