[doc] Add shape about layout improvements
eclipse-sirius/sirius-web pull request #1950
Opened 2023-04-27 12:34 UTC by gcoutable

Bug:  #1923 
# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [x] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2023-04-28 07:48 UTC, sbegaudeau requested changes

2023-04-28 07:48 UTC, sbegaudeau commented on doc/iterations/2023.6/scopes/improveEmptyNodesLayout.adoc
> +- [ ] User guide updated with screenshots
No need for a scope right know (especially given that it does not contain anything relevant for the iteration)

2023-04-28 07:48 UTC, sbegaudeau commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +We do not want to use ELK anymore. For that we need to be able to handle the lifecycle of a diagram layout from its creation to its desctruction.
One sentence per line

2023-04-28 07:48 UTC, sbegaudeau commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +In sirius-components, we are using it to compute the first layout of a diagram, or to perfrom an "arrange all" on demand.
perform

2023-04-28 07:48 UTC, sbegaudeau commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +Having two layout solutions bring some issues.
brings

2023-04-28 07:48 UTC, sbegaudeau commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +One of them is about ELK. Sometime, ELK needs to be twisted to get the result we want.
One sentence per line

2023-04-28 07:48 UTC, sbegaudeau commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +Nodes size and position should take into account, data comming from the specifier, updates comming from the user like the move or resize and, default values.
coming

2023-04-28 07:48 UTC, sbegaudeau commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +If a tool creates many nodes on the same deep, one of the node will be located where the user clicked, others node will be display in column (or row) under (like scenario 1)
at the same depth

2023-04-28 07:48 UTC, sbegaudeau commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +We should keep in mind that a tool can do anything, create, update or, remove elements. It is not because a tool is called a node creation tool that it will only be used to create something (it may b
One sentence per line

2023-04-28 07:48 UTC, sbegaudeau commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +If a tool creates many nodes, a node and one or many children, the new parent node will be created where the user clicked, children will be display starting at (0, 0) in the parent (like <<scenario-4
Copy / Paste

2023-04-28 07:48 UTC, sbegaudeau commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +Shrinking a node by moving North or West anchor can be tricky because it changes the size of the node _and_ it's position.
moving its

2023-04-28 08:14 UTC, gcoutable commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +In sirius-components, we are using it to compute the first layout of a diagram, or to perfrom an "arrange all" on demand.
done

2023-04-28 08:14 UTC, gcoutable commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +Having two layout solutions bring some issues.
done

2023-04-28 08:15 UTC, gcoutable commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +One of them is about ELK. Sometime, ELK needs to be twisted to get the result we want.
Done

2023-04-28 08:16 UTC, gcoutable commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +We do not want to use ELK anymore. For that we need to be able to handle the lifecycle of a diagram layout from its creation to its desctruction.
Done

2023-04-28 08:18 UTC, gcoutable commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +Nodes size and position should take into account, data comming from the specifier, updates comming from the user like the move or resize and, default values.
Done

2023-04-28 08:18 UTC, gcoutable commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +If a tool creates many nodes on the same deep, one of the node will be located where the user clicked, others node will be display in column (or row) under (like scenario 1)
Done

2023-04-28 08:19 UTC, gcoutable commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +We should keep in mind that a tool can do anything, create, update or, remove elements. It is not because a tool is called a node creation tool that it will only be used to create something (it may b
Done

2023-04-28 08:20 UTC, gcoutable commented on doc/iterations/2023.6/scopes/improveEmptyNodesLayout.adoc
> +- [ ] User guide updated with screenshots
Removed

2023-04-28 08:27 UTC, gcoutable commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +If a tool creates many nodes, a node and one or many children, the new parent node will be created where the user clicked, children will be display starting at (0, 0) in the parent (like <<scenario-4
done

2023-04-28 08:28 UTC, gcoutable commented on doc/iterations/2023.6/shapes/improveEmptyNodesLayout.adoc
> +Shrinking a node by moving North or West anchor can be tricky because it changes the size of the node _and_ it's position.
done

2023-05-10 13:24 UTC, sbegaudeau approved these changes

2023-05-10 13:39 UTC, merged