[2018] Displays the page of the first element selected
eclipse-sirius/sirius-web pull request #2025
Opened 2023-06-05 08:53 UTC by frouene

Bug: https://github.com/eclipse-sirius/sirius-components/issues/2018

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2023-06-05 15:04 UTC, pcdavid commented on CHANGELOG.adoc
> +- https://github.com/eclipse-sirius/sirius-components/issues/2008[#2018] [view] Fixed form editor selection to display the page containing the first element selected.
Typo: 2008 instead of 2018.

2023-06-05 15:48 UTC, pcdavid requested changes

2023-06-05 15:48 UTC, pcdavid commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/PageList.tsx
> +    }
The search is not exhaustive enough: we can have page>group>widget>style, or page>group>flexboxcontainer>widget(>style), or even page>group>flexboxcontainer>widget>changeContext>changeContext>etc. (arbitrary depth of operations inside a widget)

2023-06-05 15:51 UTC, pcdavid commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/PageList.tsx
> +    }
Clicked on (1), which is part of Page1, but the editor is still showing Page2.

![screenshot-2023-06-05_17-50](https://github.com/eclipse-sirius/sirius-components/assets/10608/a8c8aee9-5133-40dd-aa1e-68785302942f)

2023-06-06 14:36 UTC, frouene commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/PageList.tsx
> +    }
The style and operation element doesn't change the component selection in the editor.
I added the correct bahaviour for `flexboxContainer` and `toolbarAction`

2023-06-06 15:07 UTC, AxelRICHARD submitted a review, later dismissed
It seems there is a problem with the Select Widget and the form description editor.
1. Try to get a form description with two pages, each containing widgets. A select widget must be in the first page.
2. From the explorer, select a widget in the second page.
3. From the explorer, select the select widget in the first page => an exception is raised in the frontend
```
SelectInput.js:98 Uncaught TypeError: Cannot read properties of null (reading 'focus')
    at Object.focus (SelectInput.js:98:21)
    at sirius-components-formdescriptioneditors.es.js:3120:68
    at invokePassiveEffectCreate (react-dom.development.js:23487:20)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:9)
    at unstable_runWithPriority (scheduler.development.js:468:12)
    at runWithPriority$1 (react-dom.development.js:11276:10)
    at flushPassiveEffects (react-dom.development.js:23447:14)
```

2023-06-06 15:07 UTC, AxelRICHARD commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/PageList.tsx
> +  const recursiveWidgetSearch = (widget: GQLWidget, entryId: string): boolean => {
Could you move this method outside the component please? Just after `isErrorPayload` would be a better place.

2023-06-07 08:18 UTC, pcdavid approved these changes

2023-06-07 08:19 UTC, pcdavid commented
There's still @AxelRICHARD's request to improve the code and the issue with the Select widget noted above, but the functional issue I noted with the previous version is now fixed.

2023-06-07 13:06 UTC, sbegaudeau requested changes
I'll try to run the code to see the fix in action and I'll fix the two minor issues.

2023-06-07 13:06 UTC, sbegaudeau commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/MultiSelectWidget.tsx
> +      }, 50);
`setTimeout` calls need to be cleanup otherwise you have a memory leak

2023-06-07 13:06 UTC, sbegaudeau commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/SelectWidget.tsx
> +      }, 50);
`setTimeout` calls need to be cleanup otherwise you have a memory leak

2023-06-07 13:06 UTC, sbegaudeau commented on packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/PageList.tsx
> +    const entry = selection.entries?.at(0);
`selection.entries` cannot be `null` otherwise you have another major issue

2023-06-07 13:07 UTC, sbegaudeau commented on CHANGELOG.adoc
> +- https://github.com/eclipse-sirius/sirius-components/issues/2018[#2018] [view] Fixed form editor selection to display the page containing the first element selected.
It's not in `[view]` but in `[formdescriptioneditors]`

2023-06-07 13:25 UTC, frouene commented
There is an issue on the MaterialUI component (https://github.com/mui/material-ui/issues/21441) that may explain the behavior encountered with the Select widget. Adding a timeout on the focus solves the problem.

2023-06-07 13:43 UTC, sbegaudeau approved these changes

2023-06-07 13:43 UTC, merged