Add domainType on PageDescription in the view DSL
eclipse-sirius/sirius-web pull request #2043
Opened 2023-06-07 14:27 UTC by frouene

Bug: https://github.com/eclipse-sirius/sirius-components/issues/2032

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2023-06-07 15:31 UTC, sbegaudeau requested changes

2023-06-07 15:31 UTC, sbegaudeau commented on CHANGELOG.adoc
> +- https://github.com/eclipse-sirius/sirius-components/issues/2032[#2032] [form] Add domainType on PageDescription in the view DSL and takes into account the impacts for the FormDescriptionAggregator.
Could you add some information for the other changes such as the breaking change to contribute the to `IPropertiesDescriptionRegistry` which takes a PageDescription and not a FormDescription anymore and the new selection variable available in some contexts

2023-06-07 15:31 UTC, sbegaudeau commented on packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/FormDescriptionAggregator.java
> +        List<PageDescription> pageDescriptions = new ArrayList<>();
The commit message describe what the code does but not what the impact will be. Something like "Change how the precondition to create the details view is evaluated" would let others understand more clearly the impact of the change.

2023-06-07 15:31 UTC, sbegaudeau commented on packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/FormDescriptionAggregator.java
> +                    .filter(pageDescription -> pageDescription.getCanCreatePredicate().test(pageVariableManager))
Now contributors of page descriptions should have to adapt their code to handle a single object instead of a collection. Are you sure that such code like in `ViewPropertiesDescriptionRegistryConfigurer` should not be updated?

2023-06-07 15:31 UTC, sbegaudeau commented on packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/FormDescriptionAggregator.java
> +                    .filter(pageDescription -> pageDescription.getCanCreatePredicate().test(pageVariableManager))
Same comment for the canCreatePredicates of the code in `NodeStylePropertiesConfigurer` for another example. It seems that there are a lot of `self instanceof List` in those files given this change

2023-06-07 15:31 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/NodeStylePropertiesConfigurer.java
> +        this.getImageNodeStyleProperties().getPageDescriptions().forEach(registry::add);
Do we still need to create three FormDescriptions to throw them away? Couldn't we just create the PageDescriptions directly in the methods below?

2023-06-07 15:31 UTC, sbegaudeau commented on packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/FormDescriptionAggregator.java
> +            pageVariableManager.put(FormVariableProvider.SELECTION.name(), objects);
While you can add this variable here, I suspect that you would also have to make it available to the renderer too to let specifiers use it fully. Right now, my only question (I haven't tested yet) would be can I select multiple node descriptions in the explorer and still keep the existing behavior of having multiple details view to edit them? I'll try and I'll know quite soon.

2023-06-08 07:09 UTC, frouene commented on packages/forms/backend/sirius-components-collaborative-forms/src/main/java/org/eclipse/sirius/components/collaborative/forms/FormDescriptionAggregator.java
> +                    .filter(pageDescription -> pageDescription.getCanCreatePredicate().test(pageVariableManager))
Indeed, I change the `canCreatePredicate` to take into account the change in the variable.

2023-06-08 07:12 UTC, frouene commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/NodeStylePropertiesConfigurer.java
> +        this.getImageNodeStyleProperties().getPageDescriptions().forEach(registry::add);
I changed to directly used the pageDescription.

2023-06-19 08:52 UTC, sbegaudeau approved these changes

2023-06-19 12:01 UTC, merged