[2095] Add support for the creation of new edges
eclipse-sirius/sirius-web pull request #2150
Opened 2023-07-04 13:35 UTC by sbegaudeau

Bug: https://github.com/eclipse-sirius/sirius-components/issues/2095
Signed-off-by: Stéphane Bégaudeau <stephane.begaudeau@obeo.fr>

WIP edges

Signed-off-by: Stéphane Bégaudeau <stephane.begaudeau@obeo.fr>

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2023-07-06 07:54 UTC, sbegaudeau commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
> +  representationId,
These should be retrieved using the `DiagramContext`

2023-07-06 07:56 UTC, sbegaudeau commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
> +
This code and the associated state could be extracted from this component. It would simplify how the code is integrated.

2023-07-06 07:56 UTC, sbegaudeau commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/representation/DiagramRepresentation.tsx
> +          />
Useless change, use the context instead

2023-07-06 07:57 UTC, sbegaudeau commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
> +`;
Useless, can be removed

2023-07-06 07:57 UTC, sbegaudeau commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/ConnectorContextualMenu.tsx
> +/*******************************************************************************
To be extracted in a dedicated folder

2023-07-06 07:58 UTC, sbegaudeau commented
Since we have performed some improvements with @gcoutable on the integration of the direct edit, this PR should be improved to take into account them

2023-07-28 13:27 UTC, gcoutable requested changes

2023-07-28 13:27 UTC, gcoutable commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContextualMenu.tsx
> +  if (!data || connectorTools.length === 1) {
It is possible to have _data_ and no _connector tools_, a small white square is displayed.
Any source/target combination without a defined edge description is in that case.

2023-07-28 13:27 UTC, gcoutable commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContextualMenu.tsx
> +  }, [connectorTools]);
This useEffect will be called on every render, `connectorTools` is always different.

2023-07-28 13:27 UTC, gcoutable commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContextualMenu.types.ts
> +}
This interface is not needed

2023-07-28 13:27 UTC, gcoutable commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContext.types.ts
> +  setConnection: (connection: Connection) => void;
setConnection: (connection: Connection | null) => void;

2023-07-28 13:57 UTC, gcoutable commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContext.types.ts
> +  setConnection: (connection: Connection) => void;
Done

2023-07-28 13:58 UTC, gcoutable commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContextualMenu.tsx
> +  }, [connectorTools]);
We will address that later

2023-07-28 14:07 UTC, gcoutable commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContextualMenu.tsx
> +  if (!data || connectorTools.length === 1) {
Done

2023-07-28 14:07 UTC, gcoutable commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/connector/ConnectorContextualMenu.types.ts
> +}
Removed

2023-07-28 15:45 UTC, gcoutable approved these changes

2023-07-28 16:14 UTC, merged