[2204] Add styled string for tree item labels
eclipse-sirius/sirius-web pull request #2205
Opened 2023-07-25 14:20 UTC by mcharfadi

Bug: https://github.com/eclipse-sirius/sirius-components/issues/2204

2023-07-26 12:15 UTC, sbegaudeau requested changes

2023-07-26 12:15 UTC, sbegaudeau commented on packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/browser/ModelBrowserDescriptionProvider.java
> +import org.eclipse.sirius.components.trees.labels.*;
Don't use star imports

2023-07-26 12:15 UTC, sbegaudeau commented on packages/core/frontend/sirius-components-core/src/label/StyledLabel.tsx
> +    backgroundColor: 'var(--blue-lagoon-lighten-90)',
Don't use either "magic colors" nor colors from outdated style `(var--xxx)`

2023-07-26 12:15 UTC, sbegaudeau commented on packages/core/frontend/sirius-components-core/src/label/StyledLabel.type.ts
> +export interface GQLStyle {
Tons of things could be called Style, please use a more specific name `StyledStringFragment` and `StyledStringFragmentStyle`

2023-07-26 12:15 UTC, sbegaudeau commented on packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/ObjectService.java
> +        return label;
If we were to keep a `String getLabel(Object object)` method, the only valid content inside of this method would be this:

```
public String getLabel(Object object) {
    return this.getStyledLabel(object).toString();
}

public StyledString getStyledLabel(Object object) {
    // ....
}

```

2023-07-26 12:15 UTC, sbegaudeau commented on packages/trees/backend/sirius-components-trees/src/main/java/org/eclipse/sirius/components/trees/labels/Style.java
> +public record Style(String font, String backgroundColor, String foregroundColor, String strikeoutColor, String underlineColor, String borderColor, boolean isStrikedout, UnderLineStyle underLineStyle,
- Use a builder pattern to help create those objects
- Use a more meaningful name (see other comment on the matter)

2023-07-26 12:15 UTC, sbegaudeau commented on packages/trees/backend/sirius-components-trees/src/main/java/org/eclipse/sirius/components/trees/labels/StyledString.java
> +    public String getString() {
Override `toString()` instead

2023-07-26 12:15 UTC, sbegaudeau commented on packages/trees/backend/sirius-components-trees/src/main/java/org/eclipse/sirius/components/trees/labels/UnderLineStyle.java
> +    LINK,
Use exactly the CSS names

2023-07-26 12:15 UTC, sbegaudeau commented on packages/forms/backend/sirius-components-widget-reference/src/main/java/org/eclipse/sirius/components/widget/reference/browser/ModelBrowserDescriptionProvider.java
> +        Style style = new Style("", "", "", "", "", "", false, UnderLineStyle.NONE, BorderStyle.NONE);
A builder pattern is absolutely require for that

2023-11-23 20:57 UTC, sbegaudeau commented
With the introduction of the composed object service, we will now be able to move forward by merging this since we will be able to use it for some examples such as the view and domain metamodels

2024-07-23 08:55 UTC, frouene commented
Where the file `treeItemLabelStyled.jpg` is used ?

2024-07-23 09:29 UTC, mcharfadi commented
It should have been used in the changelog, I'll link it back correctly

2024-07-23 13:05 UTC, frouene requested changes

2024-07-23 13:05 UTC, frouene commented on packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/ILabelService.java
> +            return StyledString.of("");
Why don't use the same noop that for `IDefaultLabelService`

2024-07-23 13:05 UTC, frouene commented on packages/core/frontend/sirius-components-core/src/label/StyledLabel.tsx
> +export const splitText = (label: string, userInput: string | null): string[] => {
does it need to be exported ?

2024-07-23 13:05 UTC, frouene commented on packages/core/frontend/sirius-components-core/src/label/StyledLabel.tsx
> + * Copyright (c) 2023, 2024 Obeo.
wrong dates

2024-08-12 08:30 UTC, mcharfadi commented on packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/ILabelService.java
> +            return StyledString.of("");
What do you mean ? The content is the same but they don't share an interface.

2024-08-12 08:30 UTC, mcharfadi commented on packages/core/frontend/sirius-components-core/src/label/StyledLabel.tsx
> +export const splitText = (label: string, userInput: string | null): string[] => {
Yes, it's used in `FilterableSortableList`

2024-08-12 15:21 UTC, frouene commented on packages/core/frontend/sirius-components-core/src/label/StyledLabel.tsx
> +export const splitText = (label: string, userInput: string | null): string[] => {
In `FilterableSortableList`, the one used is from `'@eclipse-sirius/sirius-components-trees'`
By the way, `splitText` is duplicated in `sirius-components-trees` and `sirius-components-core`

2024-08-12 15:29 UTC, frouene commented on packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/ILabelService.java
> +            return StyledString.of("");
In `IDefaultLabelService` the NoOp impl is `return new StyledString(List.of());`
Why not use the same default impl in `ILabelService` ?
(It's just a small detail to be consistent, it doesn't really matter)

2024-08-12 15:30 UTC, mcharfadi commented on packages/core/frontend/sirius-components-core/src/label/StyledLabel.tsx
> +export const splitText = (label: string, userInput: string | null): string[] => {
You're right there is an inconsistency there.
I think `splitText `should be exported from `sirius-components-core` and `getText `should be renamed to `getTextFromStyledLabel ` and also be exported from `sirius-components-core`. Would that be okay ?

2024-08-12 15:31 UTC, mcharfadi commented on packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/api/ILabelService.java
> +            return StyledString.of("");
Okay I see, I'll make the change then.

2024-08-12 15:32 UTC, frouene commented on packages/core/frontend/sirius-components-core/src/label/StyledLabel.tsx
> +export const splitText = (label: string, userInput: string | null): string[] => {
Looks good to me

2024-08-13 08:12 UTC, frouene approved these changes

2024-08-23 19:27 UTC, sbegaudeau reviewed
I'll rebase the PR and look to fix the minor issues detected. Once it will be done, I'll test it a little to merge it if I don't encounter any major issue.

2024-08-23 19:27 UTC, sbegaudeau commented on integration-tests/cypress/e2e/project/edit/color-palette.cy.js
> +    cy.getByTestId('Color Palette').should('exist');
No need to change the data-tested, I don't even know how many tests are relying on them in Sirius Web and in other applications which would have to be updated.

2024-08-23 19:27 UTC, sbegaudeau commented on integration-tests/cypress/e2e/project/edit/explorer-filterbar.cy.js
> +    cy.getByTestId('System Robot').dblclick();
I won't comment it on every single line but those should not change

2024-08-23 19:27 UTC, sbegaudeau commented on packages/core/frontend/sirius-components-core/src/label/StyledLabel.type.ts
> +enum GQLUnderLineStyle {
Never use TypeScript `enum`, it does not do what you think it does, use unions instead

2024-08-23 19:27 UTC, sbegaudeau commented on packages/core/frontend/sirius-components-core/src/label/StyledLabel.type.ts
> +enum GQLBorderStyle {
Same comment

2024-08-23 19:27 UTC, sbegaudeau commented on packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/browser/ModelBrowsersDescriptionProvider.java
> +            label = representationMetadata.getLabel();
The reference widget does not display representations

2024-08-23 19:27 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/tree/ECoreSampleStyledLabelService.java
> +public class ECoreSampleStyledLabelService extends DefaultLabelService implements ILabelServiceDelegate {
ECore -> Ecore

2024-08-23 19:27 UTC, sbegaudeau commented on packages/trees/backend/sirius-components-collaborative-trees/src/main/resources/schema/tree.graphqls
> +}
formatting issue (two spaces vs four spaces)

2024-08-23 19:27 UTC, sbegaudeau commented on packages/trees/backend/sirius-components-trees/pom.xml
> +		</dependency>
sirius-components-core already depends on sirius-components-representations which can thus be removed as a direct dependency

2024-08-23 19:27 UTC, sbegaudeau commented on packages/trees/frontend/sirius-components-trees/src/views/__tests__/GraphqlTreeEventSubscription.test.ts
> +          isStrikedout
I won't make you change it now but I don't think that `isStrikedOut` is valid in English. I think that it should be `isStruckOut`. We will change it later

2024-08-23 19:34 UTC, sbegaudeau commented on packages/core/frontend/sirius-components-core/src/label/StyledLabel.type.ts
> +enum GQLUnderLineStyle {
Done

2024-08-23 19:34 UTC, sbegaudeau commented on packages/core/frontend/sirius-components-core/src/label/StyledLabel.type.ts
> +enum GQLBorderStyle {
Done

2024-08-23 19:36 UTC, sbegaudeau commented on packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/browser/ModelBrowsersDescriptionProvider.java
> +            label = representationMetadata.getLabel();
Done

2024-08-23 19:37 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/tree/ECoreSampleStyledLabelService.java
> +public class ECoreSampleStyledLabelService extends DefaultLabelService implements ILabelServiceDelegate {
Done

2024-08-23 19:37 UTC, sbegaudeau commented on packages/trees/backend/sirius-components-collaborative-trees/src/main/resources/schema/tree.graphqls
> +}
There were other formatting issues that I've fixed at the same time

2024-08-23 19:39 UTC, sbegaudeau commented on packages/trees/backend/sirius-components-trees/pom.xml
> +		</dependency>
Please try to be more careful with dependencies next time guys, I can't be the only one caring about things like that /cc @mcharfadi @frouene

2024-08-26 08:29 UTC, sbegaudeau reviewed
I'll wait for the build to finally merge it, I've tested it quickly and the end result looks nice

2024-08-26 09:00 UTC, sbegaudeau approved these changes

2024-08-26 09:01 UTC, merged