[doc] Add ADR for color management in View
eclipse-sirius/sirius-web pull request #2347
Opened 2023-09-05 14:11 UTC by AxelRICHARD

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [x] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2023-09-11 09:03 UTC, sbegaudeau requested changes

2023-09-11 09:03 UTC, sbegaudeau commented on doc/adrs/109_color_management_in_view.adoc
> +* sirius-web theme colors (light pink, pink, dark pink, purple)?
I would only refer to theme colors by their names in order to offer later the ability to simply change where the view model is deployed and have the colors match the new environment.

2023-09-11 09:03 UTC, sbegaudeau commented on doc/adrs/109_color_management_in_view.adoc
> +---
Honestly for that, we should simply return none as part of the options on a select when it is authorized and not return it when it is not and remove entirely from the frontend some special use case for none. It's just a value from the backend and if the frontend sends it back to the backend because the user has selected it, then the backend should unset the value. We don't need more magic about that on the frontend.

If the backend knows when none should be allowed as a value, then it can send it as an option or not and thus handle it when the value is sent back from the frontend. The frontend does not have to do anything about that, especially not hardcode support for none.

2023-09-11 09:03 UTC, sbegaudeau commented on doc/adrs/109_color_management_in_view.adoc
> +    if (colorValue.startsWith('theme.palette.primary.main')) {
`===` instead of `startsWith`

2023-09-11 09:03 UTC, sbegaudeau commented on doc/adrs/109_color_management_in_view.adoc
> +      if (shade) {
Not with a regex, it will only brings more issues

2023-09-11 09:03 UTC, sbegaudeau commented on doc/adrs/109_color_management_in_view.adoc
> +We will update `org.eclipse.sirius.web.services.explorer.ExplorerDescriptionProvider#isDeletable` and `org.eclipse.sirius.web.services.explorer.ExplorerDescriptionProvider#isEditable` to return `fals
We could also prevent the edition of the value in the details view

2023-09-11 09:03 UTC, sbegaudeau commented on doc/adrs/109_color_management_in_view.adoc
> +All View color properties are now mandatory.
Do we have / need something like that for forms?

2023-09-11 15:04 UTC, AxelRICHARD commented on doc/adrs/109_color_management_in_view.adoc
> +All View color properties are now mandatory.
No we don't. Il will create a new `DiagramDescriptionValidator `

2023-09-11 15:04 UTC, AxelRICHARD commented on doc/adrs/109_color_management_in_view.adoc
> +---
Done

2023-09-11 15:04 UTC, AxelRICHARD commented on doc/adrs/109_color_management_in_view.adoc
> +* sirius-web theme colors (light pink, pink, dark pink, purple)?
Done

2023-09-20 13:49 UTC, sbegaudeau approved these changes

2023-09-20 13:49 UTC, merged