[2162] Unable to perform two chained direct-edit
eclipse-sirius/sirius-web pull request #2364
Opened 2023-09-08 13:42 UTC by mcharfadi

Bug: https://github.com/eclipse-sirius/sirius-web/issues/2162

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2023-09-11 08:04 UTC, gcoutable requested changes, later dismissed

2023-09-11 08:04 UTC, gcoutable commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/direct-edit/DiagramDirectEditInput.tsx
> +    };
You need a ref to the parent element to force the focus on it.
You may want to support edges too; thus, `HTMLDivElement` may not be appropriate here.

2023-09-11 08:04 UTC, gcoutable commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/direct-edit/DiagramDirectEditInput.tsx
> +      let elementToFocus: HTMLDivElement | null = (parentElementRef.current?.parentNode as HTMLDivElement) ?? null;
Why do you try to focus on parentNode while `parentElementRef.current` seems to reference the parent?

2023-09-11 08:04 UTC, gcoutable commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/edge/MultiLabelEdge.tsx
> +    const elementRef = useRef<HTMLDivElement | null>(null);
You may need to put a ref on edge too

2023-09-11 14:11 UTC, sbegaudeau requested changes
If I understand things correctly, when the direct edit is triggered using the pen icon in the palette then the focus is lost (since it moves to the tool and then to the body of the document) and after that we can't trigger a new direct edit because the keydown listener on the diagram is not triggered.

I don't see why you need to give a ref from everywhere the label component is used to the very bottom of the label component in order to focus the relevant element. Couldn't you simply ask for the `diagramElementId` on Label in order to know the parent of the label element (since it's not the parent in the DOM) and then use something like this:

```
document.querySelector(`[data-id="${diagramElementId}"]`).focus();
```

2023-09-12 07:47 UTC, sbegaudeau commented
Since we need to move forward with that, I'll take it from here and ensure that it will be merged.

2023-09-12 08:31 UTC, sbegaudeau approved these changes

2023-09-12 09:00 UTC, merged