Lfa/enh/ref intermodel
eclipse-sirius/sirius-web pull request #243
Opened 2022-08-03 12:38 UTC by lfasani

This PR is related to [#1301 Add support for inter model references](https://github.com/eclipse-sirius/sirius-components/issues/1301) issue

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [X] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested? -> Not yet
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
* upload a document1 in a project
* create a new document2 in this project
* Add a reference from an object in document1 to an object in document2
* close the project and reopen it
Expected: all the changes are present (it means that save and load worked)
* download document1
Expected: the downloaded document should be the same as the original except the xmi:id and the added reference

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2022-09-26 09:54 UTC, pcdavid requested changes

2022-10-04 09:39 UTC, lfasani commented on backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/DynamicRepresentationDescriptionService.java
> +        JsonResource resource = new JSONResourceFactory().createResource(uri);
done

2022-10-04 09:39 UTC, lfasani commented on backend/sirius-web-services/src/main/java/org/eclipse/sirius/web/services/representations/ViewService.java
> +        JsonResource resource = new JSONResourceFactory().createResource(uri);
All calls to createResource(URI) have been changed to createResourceFromPath(String)

2022-10-10 12:11 UTC, sbegaudeau commented
Merged in Sirius Components

2022-10-10 12:11 UTC, closed without merging