[2552] Close the palettes on Escape
eclipse-sirius/sirius-web pull request #2652
Opened 2023-11-28 09:44 UTC by pcdavid

Bug: https://github.com/eclipse-sirius/sirius-web/issues/2552
Signed-off-by: Pierre-Charles David <pierre-charles.david@obeo.fr>

2023-11-28 09:47 UTC, sbegaudeau requested changes

2023-11-28 09:47 UTC, sbegaudeau commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
> +
This could belong in the palette hooks, let's try not to add new behavior in the diagram renderer

2023-11-28 13:37 UTC, pcdavid commented on packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/DiagramRenderer.tsx
> +
Done.

2023-11-30 13:32 UTC, sbegaudeau approved these changes

2023-11-30 13:52 UTC, merged