[2765] Add initial version of a portal representation
eclipse-sirius/sirius-web pull request #2811
Opened 2023-12-11 16:05 UTC by pcdavid

- [releng] Add missing test resources for new projects
- [2765] Add initial version of a portal representation

2024-01-04 09:31 UTC, sbegaudeau requested changes
I have not executed the code but since I've seen it multiple times, I believe that it should work. Could you add a very basic Cypress test creating an empty portal and verifying that it is displayed too in order to ensure that we don't break everything without noticing it, thanks.

2024-01-04 09:31 UTC, sbegaudeau commented on packages/portals/backend/pom.xml
> +	<version>2023.10.9</version>
Will have to be updated

2024-01-04 09:31 UTC, sbegaudeau commented on packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/PortalEventProcessor.java
> +    private final AtomicReference<Portal> currentPortal;
I don't think we need an atomic reference here, a regular field should work just fine but that's the same issue in other representations (and of course this would have no sense in being final)

2024-01-04 09:31 UTC, sbegaudeau commented on packages/portals/frontend/sirius-components-portals/src/hooks/usePortalMutations.ts
> +export const usePortalMutations = (editingContextId: string, portalId: string): UsePortalMutationsValue => {
Add support for displaying errors with toast for all mutations

2024-01-04 09:31 UTC, sbegaudeau commented on packages/portals/frontend/sirius-components-portals/tsconfig.json
> +  "extends": "@eclipse-sirius/sirius-components-tsconfig/react-library.json",
Please start (or switch quickly) to the strict version for such as new project

2024-01-04 09:31 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web/src/portals.css
> +  background: var(--blue-lagoon);
Use the proper color, blue-lagoon must have been deprecated years ago? It's mostly used by the soon to be deleted sporty code now.

2024-01-04 09:31 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web/src/portals.css
> +  background: var(--blue-lagoon);
Can't this file be located in sirius-components-portals frontend instead? Or could this be done another way but directly in sirius-components-portals to not have everybody do this in their application.

2024-01-04 10:39 UTC, pcdavid commented on packages/portals/backend/pom.xml
> +	<version>2023.10.9</version>
Done.

2024-01-04 10:44 UTC, pcdavid commented on packages/portals/backend/sirius-components-collaborative-portals/src/main/java/org/eclipse/sirius/components/collaborative/portals/PortalEventProcessor.java
> +    private final AtomicReference<Portal> currentPortal;
Done (only for this processor).

2024-01-04 13:56 UTC, pcdavid commented on packages/portals/frontend/sirius-components-portals/tsconfig.json
> +  "extends": "@eclipse-sirius/sirius-components-tsconfig/react-library.json",
Done. And fixed the few typing issues it revealed.

2024-01-04 14:53 UTC, pcdavid commented on packages/portals/frontend/sirius-components-portals/src/hooks/usePortalMutations.ts
> +export const usePortalMutations = (editingContextId: string, portalId: string): UsePortalMutationsValue => {
Done. I've attempted a semi-generic (at least locally) hook for reporting errors from mutations, comments welcome.

2024-01-04 15:07 UTC, pcdavid commented on packages/sirius-web/frontend/sirius-web/src/portals.css
> +  background: var(--blue-lagoon);
I tried that, but couldn't make it work.

* Put the style in `packages/portals/frontend/sirius-components-portals/src/representations/portal.css`.
* Added `import './portal.css';` in `PortalRepresentation.tsx`.
* Added `css()` from `rollup-plugin-import-css` in the Vite config (and added `rollup-plugin-import-css` in `devDependencies`).

My custom color is not picked up. Do you see what I'm missing?

2024-01-04 15:43 UTC, gcoutable commented on packages/sirius-web/frontend/sirius-web/src/portals.css
> +  background: var(--blue-lagoon);
`import './portal.css';` can be done in `packages/sirius-web/frontend/sirius-web/index.tsx` like others.
I don't have any other solution in mind.

2024-01-05 09:38 UTC, pcdavid commented
Note: the only test failing is in `project/diagrams/diagram-contextual-palette.cy.js`. It's completely unrelated to this PR, and unfortunately known to be unreliable.

2024-01-08 12:48 UTC, sbegaudeau approved these changes
I'lLet's approve this to be able to merge it. @pcdavid feel free to do it, since I have a couple of other things to review you may end up doing it faster than me, in case it needs to be rebased for example.

2024-01-08 14:17 UTC, merged