[2784] Add more monitored functions
eclipse-sirius/sirius-web pull request #2820
Opened 2023-12-14 08:42 UTC by mcharfadi

Bug: https://github.com/eclipse-sirius/sirius-web/issues/2784

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2023-12-14 08:44 UTC, mcharfadi commented on packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessor.java
> +        Timer doHandleTimer = Timer.builder(Monitoring.EDITING_CONTEXT_EVENT_PROCESSOR_LOADING).tag("inputId", input.id().toString()).register(meterRegistry);
not sure about keeping the id as a tag here

2023-12-14 15:02 UTC, sbegaudeau requested changes

2023-12-14 15:02 UTC, sbegaudeau commented on packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/api/Monitoring.java
> +    public static final String DIAGRAM_EVENT_PROCESSOR_LOADING = "siriusweb_diagrameventprocessor_loading";
Do not reference any specific representation here, no diagram nor any other representation

2023-12-14 15:02 UTC, sbegaudeau commented on packages/charts/backend/sirius-components-collaborative-charts/src/main/java/org/eclipse/sirius/components/collaborative/charts/HierarchyCreationService.java
> +    @Timed(value = Monitoring.REPRESENTATION_EVENT_PROCESSOR_REFRESH, extraTags = {Monitoring.NAME, "hierarchy"})
Can't all those `@Timed` annotation on the creation of the representation be instead put around the creation of the representation event processor factory in `EditingContextEventProcessor#aquireRepresentationEventProcessor` in order to have something generic and not tied to some representation-specific service

2023-12-14 15:02 UTC, sbegaudeau commented on packages/charts/backend/sirius-components-collaborative-charts/src/main/java/org/eclipse/sirius/components/collaborative/charts/HierarchyCreationService.java
> +    @Timed(value = Monitoring.REPRESENTATION_EVENT_PROCESSOR_REFRESH, extraTags = {Monitoring.NAME, "hierarchy"})
Can't all those `@Timed` annotation on the refresh of the representation be instead put around the refresh of the representation event factory in `EditingContextEventProcessor#setupChangeDescriptionSinkConsumer` and `EditingContextEventProcessor#refreshOtherRepresentations(...)` when calling representationEventProcessor.refresh(...)`. I don't want to have to tell all those who will write their own representation to setup things like that.

2023-12-14 15:02 UTC, sbegaudeau commented on packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessor.java
> +    public EditingContextEventProcessor(EditingContextEventProcessorParameters parameters, MeterRegistry meterRegistry) {
Please put the `meterRegistry` in the `parameters`, same thing for the representations event processor if that's needed

2023-12-14 15:02 UTC, sbegaudeau commented on packages/charts/backend/sirius-components-collaborative-charts/src/main/java/org/eclipse/sirius/components/collaborative/charts/CreateHierarchyEventHandler.java
> +    @Timed(value = Monitoring.EVENT_HANDLER)
Why do we need to modify around 100 files to add those kind of timers if we monitor the time taken by the execution of an input in `EditingContextEventProcessor#handle`? I don't think we will spend that much time iterating on the representation event processors to find the right one and on the event handlers to find the right one too.

2023-12-15 14:07 UTC, sbegaudeau approved these changes

2023-12-15 14:07 UTC, merged