Lfa/enh/gantt crud task
eclipse-sirius/sirius-web pull request #2867
Opened 2023-12-29 17:49 UTC by lfasani

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [X] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2024-01-03 15:21 UTC, frouene requested changes
I have an error when initializing a taskStudio `TaskStudioTemplatesInitializer`, the model task_example.task has not been updated and still contains `startDate` elements.

2024-01-03 15:21 UTC, frouene commented on packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/AbstractTaskPropertiesConfigurer.java
> +     */
empty javadoc

2024-01-03 15:21 UTC, frouene commented on packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/TaskJavaService.java
> +            if (abstractTask.getEndTime() != null && abstractTask.getStartTime() != null) {
I don't understand this condition and the values set to task startTime and EndTime

2024-01-03 15:21 UTC, frouene commented on packages/core/backend/sirius-components-graphql-api/src/main/java/org/eclipse/sirius/components/graphql/api/InstantScalarType.java
> + * @author Laurent Fasani
why this change in author format ?

2024-01-03 15:21 UTC, frouene commented on packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/GanttElementFactory.java
> +                })
This can be simplified by `Comparator.comparing(task -> task.detail().startTime())`

2024-01-03 15:21 UTC, frouene commented on packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/GanttElementFactory.java
> +                .findFirst()
instead of `sorted` + `findFirst` prefer `min`
Something like `subTasks.stream()
.filter(task -> task.detail().startTime() != null)
.min(Comparator.comparing(task -> task.detail().startTime()))
.map(task -> task.detail().startTime())
.orElse(props.detail().startTime());`

2024-01-03 15:21 UTC, frouene commented on packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/GanttElementFactory.java
> +                .findFirst()
same remark

2024-01-03 15:21 UTC, frouene commented on packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/TaskDetail.java
>          Objects.requireNonNull(progress);
progress is a primitive type and cannot be null

2024-01-03 15:21 UTC, frouene commented on packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/elements/TaskElementProps.java
> +public record TaskElementProps(String id, String descriptionId, String targetObjectId, String targetObjectKind, String targetObjectLabel, TaskDetail detail, List<String> dependencyObjectIds, List<Ele
Add check for dependencyObjectIds `nonNull`

2024-01-03 15:21 UTC, frouene commented on packages/gantt/backend/sirius-components-collaborative-gantt/src/main/resources/schema/gantt.graphqls
> +  computeStartEndDynamically: Boolean
is there a reason to keep this boolean optional?

2024-01-03 15:21 UTC, frouene commented on packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/service/GanttTaskService.java
> +    private IFeedbackMessageService feedbackMessageService;
may be final

2024-01-03 15:21 UTC, frouene commented on packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/service/GanttTaskService.java
> +            Optional<Object> targetObjectOpt = Optional.empty();
`targetObjectOpt` initial value is never used

2024-01-03 15:21 UTC, frouene commented on packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.tsx
> +  const onwheel = (wheelEvent: WheelEvent) => {
`onWheel` instead ?

2024-01-03 15:21 UTC, frouene commented on packages/gantt/frontend/sirius-components-gantt/src/representation/GanttRepresentation.tsx
> +  const isStandardErrorPayload = (field): field is GQLErrorPayload => field.__typename === 'ErrorPayload';
could be moved outside the component

2024-01-03 15:27 UTC, lfasani commented on packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/AbstractTaskPropertiesConfigurer.java
> +     */
done

2024-01-03 15:39 UTC, lfasani commented on packages/core/backend/sirius-components-graphql-api/src/main/java/org/eclipse/sirius/components/graphql/api/InstantScalarType.java
> + * @author Laurent Fasani
I do not know. New classes are created with java doc `@author ${user}`
I updated my configuration to have lfasani in the future

2024-01-03 15:50 UTC, lfasani commented on packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/GanttElementFactory.java
> +                })
done

2024-01-03 15:55 UTC, lfasani commented on packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/GanttElementFactory.java
> +                .findFirst()
yes it is better, thx

2024-01-03 15:55 UTC, lfasani commented on packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/GanttElementFactory.java
> +                .findFirst()
done

2024-01-03 15:56 UTC, lfasani commented on packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/TaskDetail.java
>          Objects.requireNonNull(progress);
done

2024-01-03 15:57 UTC, lfasani commented on packages/gantt/backend/sirius-components-gantt/src/main/java/org/eclipse/sirius/components/gantt/renderer/elements/TaskElementProps.java
> +public record TaskElementProps(String id, String descriptionId, String targetObjectId, String targetObjectKind, String targetObjectLabel, TaskDetail detail, List<String> dependencyObjectIds, List<Ele
done

2024-01-03 16:01 UTC, lfasani commented on packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/view/TaskJavaService.java
> +            if (abstractTask.getEndTime() != null && abstractTask.getStartTime() != null) {
I added this comment `The new task follows the context task and has the same duration than the context task.`

2024-01-03 16:03 UTC, lfasani commented on packages/gantt/backend/sirius-components-collaborative-gantt/src/main/resources/schema/gantt.graphqls
> +  computeStartEndDynamically: Boolean
no. I changed it

2024-01-03 16:04 UTC, lfasani commented on packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/service/GanttTaskService.java
> +    private IFeedbackMessageService feedbackMessageService;
done

2024-01-03 16:06 UTC, lfasani commented on packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/service/GanttTaskService.java
> +            Optional<Object> targetObjectOpt = Optional.empty();
so what? you would prefer that I initialize the value with null?

2024-01-03 16:07 UTC, lfasani commented on packages/gantt/frontend/sirius-components-gantt/src/representation/Gantt.tsx
> +  const onwheel = (wheelEvent: WheelEvent) => {
done

2024-01-03 16:11 UTC, frouene commented on packages/gantt/backend/sirius-components-collaborative-gantt/src/main/java/org/eclipse/sirius/components/collaborative/gantt/service/GanttTaskService.java
> +            Optional<Object> targetObjectOpt = Optional.empty();
No, it's just that the `= Optional.empty()` is useless, cause `targetObjectOpt` is always set (if-else)  in the following code.
It's just detail, not realy relevant.

2024-01-03 16:14 UTC, lfasani commented
> I have an error when initializing a taskStudio `TaskStudioTemplatesInitializer`, the model task_example.task has not been updated and still contains `startDate` elements.

Oh my god. I had completely changed that creating the exmaple with code and getting rid of `task_example.task` but I think it must has been lost in the rebase with conflict resolution.

2024-01-09 08:41 UTC, frouene approved these changes

2024-01-09 09:21 UTC, merged