[3000] Make portals with representations open in "direct" mode
eclipse-sirius/sirius-web pull request #3034
Opened 2024-01-29 16:18 UTC by pcdavid

Bug: https://github.com/eclipse-sirius/sirius-web/issues/3000
Signed-off-by: Pierre-Charles David <pierre-charles.david@obeo.fr>

2024-01-30 10:37 UTC, frouene requested changes
When adding an existing portal in a new portal, the existing portal is always in read-only mode
![portal_default_mode](https://github.com/eclipse-sirius/sirius-web/assets/128395825/b2e0307b-112d-45fc-a306-50ef79e8bf73)

2024-01-30 14:10 UTC, pcdavid commented
> When adding an existing portal in a new portal, the existing portal is always in read-only mode

I *think* this is fixed in the new version.

2024-01-31 07:40 UTC, frouene approved these changes

2024-01-31 08:11 UTC, pcdavid commented
I've relaunched tests, there was 1 failure in `portal.cy.ts`. They all worked locally.

2024-01-31 15:44 UTC, merged