[3015] Handle lane selection and editing in Deck
eclipse-sirius/sirius-web pull request #3038
Opened 2024-01-30 11:20 UTC by florianbarbin

See bug #3015 

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2024-02-01 17:00 UTC, frouene requested changes
When testing selection and direct edit, it's working.
There is however, a strange behavior with the `F2`. It's working the first time but if the lane stay selected (for example after `escape`) then a new `F2` doesn't trigger direct edit.

2024-02-01 17:00 UTC, frouene commented on packages/deck/frontend/sirius-components-deck/src/representation/DeckRepresentation.tsx
> +              label: '',
Even if it's no use today, wouldn't it be better to set a kind and a label?
`kind: 'lane'`
`label: lane.label`

2024-02-01 17:00 UTC, frouene commented on packages/deck/frontend/sirius-components-deck/src/laneHeader/DeckLaneHeader.types.ts
> +  t: (value: string) => string;
could you use an explicite variable name.

2024-02-01 17:00 UTC, frouene commented on integration-tests/cypress/e2e/project/deck/deck-lane.cy.ts
> +  it.only('We verify the lane direct edit.', () => {
`only` !

2024-02-06 10:13 UTC, florianbarbin commented on integration-tests/cypress/e2e/project/deck/deck-lane.cy.ts
> +  it.only('We verify the lane direct edit.', () => {
done

2024-02-06 10:13 UTC, florianbarbin commented on packages/deck/frontend/sirius-components-deck/src/laneHeader/DeckLaneHeader.types.ts
> +  t: (value: string) => string;
done

2024-02-06 10:13 UTC, florianbarbin commented on packages/deck/frontend/sirius-components-deck/src/representation/DeckRepresentation.tsx
> +              label: '',
done

2024-02-06 10:19 UTC, florianbarbin commented
> When testing selection and direct edit, it's working. There is however, a strange behavior with the `F2`. It's working the first time but if the lane stay selected (for example after `escape`) then a new `F2` doesn't trigger direct edit.

I raise an issue for this point: https://github.com/eclipse-sirius/sirius-web/issues/3070

2024-02-06 13:42 UTC, frouene approved these changes

2024-02-06 14:09 UTC, merged