[WIP][3220] Add documentation for Deck
eclipse-sirius/sirius-web pull request #3233
Opened 2024-03-13 15:02 UTC by lfasani

Bug: https://github.com/eclipse-sirius/sirius-web/issues/3220

# Pull request template

## General purpose
What is the main goal of this pull request?
- [X] Bug fixes
- [ ] New features
- [X] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

2024-03-15 10:15 UTC, frouene requested changes

2024-03-15 10:15 UTC, frouene commented on packages/deck/backend/sirius-components-deck/src/main/java/org/eclipse/sirius/components/deck/renderer/component/CardComponent.java
> +                })
no need for return, it could be done with expression lambda

2024-03-15 10:15 UTC, frouene commented on packages/deck/backend/sirius-components-deck/src/main/java/org/eclipse/sirius/components/deck/renderer/component/LaneComponent.java
> +            })
no need for return, it could be done with expression lambda

2024-03-15 10:15 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +This chapter explains how to configure a `Deck` representation in the `View` model
End ponctuation is missing

2024-03-15 10:15 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +A `Deck` representation is composed with many `Lanes` containing many `Cards`
End ponctuation is missing

2024-03-15 10:15 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +image::images/deck-overview.png[Deck representation overview]
I'm not sure about the style used for this example (in particular colors)

2024-03-15 10:15 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +To define how your model is represented with a `Deck` representation, the specifier needs to create a `DeckDescription` in the `View` model
End ponctuation is missing

2024-03-15 10:15 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +* `Semantic Candidates Expression`: An expression that returns one or more semantic elements. Each semantic element will be represented by a lane
One line per sentence

2024-03-15 10:15 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +* `Is Collapsible Expression`: An boolean expression. If true, it is possible to collapse the lane hence hidding all the contained cards
one line per sentence

2024-03-15 10:15 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +* `Semantic Candidates Expression`: An expression that returns one or more semantic elements. Each semantic element will be represented by a `Card`
one line per sentence

2024-03-15 10:15 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +** `self` variable is the semantic element associated the `Deck`
associated to the Deck ?

2024-03-15 10:15 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +** `self` variable is the semantic element associated the `Lane`
associated to the Lane ?

2024-03-15 10:15 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +* `Description Expression`: The description of the card
An expression that defines the description of the card ?

2024-03-15 10:15 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +* `Change Context`: It allows to change the `self` value. But typically this operation is usefull if you just want to call a java service that will implement the tool behavior.
One line per sentence

2024-03-15 10:15 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +** `index`: The new index of the dropped lane. First position corresponds to zero and last position corresponds to the number of lanes.
One line per sentence

2024-03-15 10:15 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +* `Create Card Tool`: This tool defines the behavior for the button to add a card
End ponctuation is missing

2024-03-15 10:15 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +** `label`: The new value of the label.
Why new only for the label ?

2024-03-15 10:15 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +* `Delete Card Tool`: This tool defines the behavior for the delete button on a card
End ponctuation is missing

2024-03-15 10:15 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +** `index`: Index of the card among the cards of the new lane. First position corresponds to zero and last position corresponds to the number of cards in the lane.
One line per sentence

2024-03-15 10:15 UTC, frouene commented on doc/user/representation-deck.adoc
> +The edit text area of a `Lane` or a `Card` first select and then click in the text area
End ponctuation is missing

2024-03-15 10:15 UTC, frouene commented on doc/user/representation-deck.adoc
> +The edit text area of a `Lane` or a `Card` first select and then click in the text area
To edit text area... ?

2024-03-15 10:15 UTC, frouene commented on doc/user/representation-deck.adoc
> +You have the ability to show individual card or hide the whole cards of a lane using expand button.
In this doc, there is no reference to the possibility of making Drag and Drop

2024-03-15 10:32 UTC, florianbarbin requested changes

2024-03-15 10:32 UTC, florianbarbin commented on doc/user/representation-deck.adoc
> +The edit text area of a `Lane` or a `Card` first select and then click in the text area
Also possible with F2

2024-03-15 10:32 UTC, florianbarbin commented on doc/user/representation-deck.adoc
> +* `Toogle full screen mode` : It allows to display the representation in full screen
Toggle

2024-03-15 10:32 UTC, florianbarbin commented on doc/user/representation-deck.adoc
> +You have the ability to show individual card or hide the whole cards of a lane using expand button.
Typo: to show individual card**s** ... using **the** expand button

2024-03-15 10:32 UTC, florianbarbin commented on doc/specifier/representation-deck.adoc
> +A tool provides access to variables usefull in the context of the tool and execute the operations associated to the tool.
Typo: ...  of the tool and execute**s** the operations associated ~~to~~ **with** the tool.

2024-03-15 10:32 UTC, florianbarbin commented on doc/specifier/representation-deck.adoc
> +* `Change Context`: It allows to change the `self` value. But typically this operation is usefull if you just want to call a java service that will implement the tool behavior.
useful not usefull

2024-03-15 10:32 UTC, florianbarbin commented on doc/specifier/representation-deck.adoc
> +A tool provides access to variables usefull in the context of the tool and execute the operations associated to the tool.
useful not usefull

2024-03-15 10:32 UTC, florianbarbin commented on doc/specifier/representation-deck.adoc
> +* `Is Collapsible Expression`: An boolean expression. If true, it is possible to collapse the lane hence hidding all the contained cards
hiding not hidding

2024-03-15 10:32 UTC, florianbarbin commented on doc/specifier/representation-deck.adoc
> +It is possible to define the style of the lane adding a `StyleDescription` in the `LaneDescription`.
of the lane **by** adding a

2024-03-15 10:32 UTC, florianbarbin commented on doc/specifier/representation-deck.adoc
> +It is possible to define the *background color* of the `Deck` representation adding a `StyleDescription` in the `DeckDescription`.
by adding

2024-03-15 14:10 UTC, lfasani commented on doc/specifier/representation-deck.adoc
> +image::images/deck-overview.png[Deck representation overview]
I made an arbitrary choice. The aim is to clearly identify the custom color

2024-03-15 14:12 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +image::images/deck-overview.png[Deck representation overview]
Ok, it works for me

2024-03-15 15:07 UTC, lfasani commented on doc/user/representation-deck.adoc
> +You have the ability to show individual card or hide the whole cards of a lane using expand button.
I added a sentence

2024-03-15 15:19 UTC, florianbarbin approved these changes

2024-03-15 15:28 UTC, frouene requested changes

2024-03-15 15:28 UTC, frouene commented on doc/specifier/representation-deck.adoc
> +** `self`:
The `self` variable has no description

2024-03-15 16:26 UTC, lfasani commented on doc/specifier/representation-deck.adoc
> +** `self`:
arf: we are close!
done

2024-03-18 07:34 UTC, frouene approved these changes

2024-03-18 08:35 UTC, merged