[doc] Add ADR on model migration
eclipse-sirius/sirius-web pull request #3281
Opened 2024-03-25 10:47 UTC by mcharfadi

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2024-03-28 14:12 UTC, sbegaudeau requested changes

2024-03-28 14:12 UTC, sbegaudeau commented on doc/adrs/142_add_support_for_emf_models_migration.adoc
> +        this.version = version;
The version should be required too, we can initialize it to something arbitrary old for existing models lacking a version

2024-03-28 14:12 UTC, sbegaudeau commented on doc/adrs/142_add_support_for_emf_models_migration.adoc
> +                filter(iMigrationParticipant -> iMigrationParticipant.canHandle(this.version))
Just use the version provided by the migration participant and check that its above the version currently consider. No need for a canHandle method here.

2024-03-28 14:12 UTC, sbegaudeau commented on doc/adrs/142_add_support_for_emf_models_migration.adoc
> +    private final List<IMigrationParticipant> iMigrationParticipants;
`iMigrationParticipant(s)` -> `migrationParticipant(s)`

2024-03-28 14:12 UTC, sbegaudeau commented on doc/adrs/142_add_support_for_emf_models_migration.adoc
> +    boolean canHandle(String currentFileVersion);
No need for every single migration participant to compare their version and the current version, you can remove this `canHandle` method

2024-03-28 14:12 UTC, sbegaudeau commented on doc/adrs/142_add_support_for_emf_models_migration.adoc
> +    String getMigrationParticipantVersion();
`getVersion` is enough, you know that it's a migration participant already

2024-03-28 14:12 UTC, sbegaudeau commented on doc/adrs/142_add_support_for_emf_models_migration.adoc
> +    EStructuralFeature getLocalElement(EClass eClass,  String namespace, String oldName);
Use meaningful names contrary to the one provided by EMF. Here, it should be something like:

```
EStructuralFeature getStructuralFeature(EClass eClass, String featureName)
```

What is the `namespace`? Is that relevant for us?

2024-03-28 14:12 UTC, sbegaudeau commented on doc/adrs/142_add_support_for_emf_models_migration.adoc
> +public class MigrationExtendedMetaData extends BasicExtendedMetaData {
Shouldn't that be the signature of `IMigrationParticipant`?

2024-03-28 14:12 UTC, sbegaudeau commented on doc/adrs/142_add_support_for_emf_models_migration.adoc
> +    }
We don't need to code that in every migration participant

2024-03-28 14:12 UTC, sbegaudeau commented on doc/adrs/142_add_support_for_emf_models_migration.adoc
> +    EStructuralFeature getLocalElement(EClass eClass,  String namespace, String oldName);
You will need to ensure that we don't need to override every single methods of the interface `IMigrationParticipant`. If one needs to just rename an attribute, they should not be asked to retrieve classes, packages, etc.

2024-03-28 14:12 UTC, sbegaudeau commented on doc/adrs/142_add_support_for_emf_models_migration.adoc
> +----
Duplicate? Or did I miss anything

2024-03-28 14:12 UTC, sbegaudeau commented on doc/adrs/142_add_support_for_emf_models_migration.adoc
> +In each method overridden, we call the corresponding method from `IMigrationParticipant` if it has a lesser version than the one used to instantiate the `MigrationExtendedMetaData`.
You are not talking about where this version will be stored? Something like a `migration` property at the root of the JSON document would be helpful but you need to serialize it and retrieve it which will require an update to sirius-emf-json. Preferably just a simple API to add whatever we need in the JSON document as a post process for exemple (but that will require a simple ADR on the EMFJson side). Anyway, you need to store something, somewhere for view, domain and other models that indicate the last version used for the migration. We could even store the name of the migration participant used to know quickly what has been the latest migration

```
{
  "json": {
    "version": "1.0",
    "encoding": "UTF-8"
  },
  "migration": {
    "lastMigrationPerformed": "NameFeatureChangelMigrationParticipant",
    "version": "202404221458"
  },
  "ns": {},
  "content": []
}
```

2024-03-28 14:12 UTC, sbegaudeau commented on doc/adrs/142_add_support_for_emf_models_migration.adoc
> +        }
Start thinking about the first concrete use case that this API should fulfill.

An attribute has disappeared (Node#labelExpression) and for those who had some expressions in this attribute, we need instead to create a new child (Node#insideLabel: InsideLabel) and set the expression on the newly created child (InsideLabel#labelExpression). I have a couple of other use cases in mind (there are a couple of attributes to rename for example but that's the first use case for the iteration).

No need to update the ADR for that use case, but when you will start implementing it, this is the first use case.

2024-03-28 16:12 UTC, mcharfadi commented on doc/adrs/142_add_support_for_emf_models_migration.adoc
> +public class MigrationExtendedMetaData extends BasicExtendedMetaData {
Yes indeed

2024-03-28 16:17 UTC, mcharfadi commented on doc/adrs/142_add_support_for_emf_models_migration.adoc
> +    EStructuralFeature getLocalElement(EClass eClass,  String namespace, String oldName);
Okay I thought I would be using the same name as the one provided by EMF. 
I also wanted to have the same methods in MigrationExtendedMetaData and the MigrationParticipant but I should only offer a few methods in MigrationParticipant to be implemented then, right ?

2024-04-10 12:52 UTC, sbegaudeau approved these changes

2024-04-10 12:52 UTC, merged