[3303] Use common identification strategy for transient representations
eclipse-sirius/sirius-web pull request #3336
Opened 2024-04-05 09:04 UTC by pcdavid

- **[3303] Add ADR for contributing representation metadata for transient representations**
- **[3303] Use common identification strategy for transient representations**

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2024-04-10 18:54 UTC, sbegaudeau requested changes

2024-04-10 18:54 UTC, sbegaudeau commented on packages/forms/backend/sirius-components-collaborative-widget-reference/src/test/java/org/eclipse/sirius/components/collaborative/widget/reference/providers/ModelBrowserDescriptionProviderTest.java
> +    public void testTreeIdFormat() {
While this test may be interesting, the real test that I'll need is, in Sirius Web, to be able to do:

```
query getRepresentationMetadata($editingContextId: ID!, $representationId: ID!) {
  viewer {
    editingContext(editingContextId: $editingContextId) {
      representation(representationId: $representationId) {
        id
        description {
          id
        }
      }
    }
  }
}
```

And see that working for both transient and persisted representations without having to be subscribed to the representation event processor. This is what's blocking me to move forward.

2024-04-10 18:54 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/UUIDParser.java
> +    }
I don't think we should be making assumptions based on UUID's only.

2024-04-10 18:54 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/services/PersistentRepresentationMetadataProvider.java
> +        return new UUIDParser().canHandle(representationId);
Test if the representation exists in the database with representationDataSearchService instead. "Our persistent representations and only them will use UUIDs" that may not be the case for possible extensions. They should try to respect that but by checking in the database we have a definitive answer.

2024-04-10 18:54 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-services-api/src/main/java/org/eclipse/sirius/web/services/api/id/IDParser.java
> +
Same comment as in the other architecture, the real test to determine if we can handle representation metadata for persisted representation is whether or not they exist.

2024-04-10 18:54 UTC, sbegaudeau commented on packages/forms/backend/sirius-components-collaborative-widget-reference/src/test/java/org/eclipse/sirius/components/collaborative/widget/reference/providers/ModelBrowserDescriptionProviderTest.java
> +    public void testTreeIdFormat() {
And thus not having to rely on the `EditingContextEventProcessorRegistry` in `EditingContextRepresentationDataFetcher`

2024-04-10 19:05 UTC, pcdavid commented
This is not actually ready for review, but I wanted to get the test results.

2024-04-18 09:05 UTC, pcdavid commented
The 2 e2e test failures in the last build are unrelated (node aspect ratio), and unreliable (they were OK in the previous build on the exact same commit).

2024-04-25 13:29 UTC, sbegaudeau commented
I've rebased the PR with some additional tests leveraging the work done in the PR (retrieval of the palette, retrieval of the reference widget options and retrieval of the help text on a form widget). I'll look at one or more additional details, review the new code coverage score which should be even better now and merge it.

2024-04-25 15:27 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/representation/services/RepresentationMetadataSearchService.java
> +        if (representationId.startsWith(ExplorerDescriptionProvider.PREFIX)) {
This is a duplicate of RepresentationApplicationService1findRepresentationMetadataById, it was a mistake on my side.

2024-04-25 17:17 UTC, sbegaudeau approved these changes

2024-04-25 17:18 UTC, merged