WIP Add shape for copy paste support
eclipse-sirius/sirius-web pull request #3739
Opened 2024-07-10 11:06 UTC by lfasani

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [X] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [x] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2024-07-10 11:51 UTC, sbegaudeau reviewed
Please only use the labels `pr: xxx` and `priority: xxx` for pull requests

2024-07-10 12:12 UTC, sbegaudeau requested changes
I've just reviewed the first part of the document but it does not match what was discussed.

2024-07-10 12:12 UTC, sbegaudeau commented on doc/iterations/2024.9/add_support_for_copy_paste.adoc
> += Add support for copy paste
None of this work is related to an action to copy nor the action of pasting at all. It is explicitly the exclusion of both of these use cases that has motivated the inclusion of this task in this iteration. The only technical perimeter that we agreed on considering for this iteration is an action to duplicate semantic elements.

The major difference being that the duplication is instantaneous. In the perimeter of this work, one cannot copy a semantic element from Sirius Web and paste it elsewhere (Microsoft Word, an email, another tab of Sirius Web, etc) nor copying something from outside (Microsoft Excel for example) and paste it in Sirius Web.

Copying and pasting bring significant technical challenges that we decided not to tackle on purpose. Duplicating is hard enough to perform. Here, there will be one action (duplicating) which will copy and paste at once.

Nothing here, should mention copying or pasting, this is not the function nor technical perimeter considered for this iteration.

2024-07-10 12:12 UTC, sbegaudeau commented on doc/iterations/2024.9/add_support_for_copy_paste.adoc
> +Currently, it is not possible to copy and paste something in Sirius Web.
duplicate

2024-07-10 12:12 UTC, sbegaudeau commented on doc/iterations/2024.9/add_support_for_copy_paste.adoc
> +The effect is that the copied object is duplicated into the object where it is pasted.
Those are some of the various use cases that have been explicitly excluded from this work.

2024-07-10 12:12 UTC, sbegaudeau commented on doc/iterations/2024.9/add_support_for_copy_paste.adoc
> +* a document in the Explorer Tree will paste into the document
In a first version, given the appetite we have for this feature, only semantic elements based on EMF from the explorer can be duplicated, using a dedicated dialog showing only the valid locations where the object can be pasted.

2024-07-10 12:12 UTC, sbegaudeau commented on doc/iterations/2024.9/add_support_for_copy_paste.adoc
> +`Paste` action is added in contextual menu on tree items in `Explorer` except for representations.
No shortcut will be available for that, this is not about copying and pasting

2024-07-10 16:14 UTC, lfasani commented on doc/iterations/2024.9/add_support_for_copy_paste.adoc
> += Add support for copy paste
The shape has been completely updated for fulfilling the duplicate specification

2024-07-11 06:16 UTC, frouene commented on doc/iterations/2024.9/add_support_for_object_duplication.adoc
> +A valid target container is an object that owns at least one multi-valued containment feature that can contain the object about to be duplicated.
Only works for multi-valued feature ?
It  won't be possible to duplicate an object to another mono-valued feature ?

2024-07-11 07:48 UTC, lfasani commented on doc/iterations/2024.9/add_support_for_object_duplication.adoc
> +A valid target container is an object that owns at least one multi-valued containment feature that can contain the object about to be duplicated.
we could accept containment mono-valued feature is not set with a non-null value.

2024-07-15 21:32 UTC, sbegaudeau approved these changes
👍

2024-07-15 21:33 UTC, merged