[3740] Add support for object duplication from Explorer
eclipse-sirius/sirius-web pull request #3798
Opened 2024-07-19 14:55 UTC by lfasani

Bug: https://github.com/eclipse-sirius/sirius-web/issues/3740

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [X] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [x] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2024-07-22 08:09 UTC, lfasani commented
It would be better if, when opening the dialog, the container of the object to duplicate were selected.
Because most of the time, the user wants to duplicate in the same container or in a container that is close in the tree.

2024-09-18 14:27 UTC, lfasani commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerDomainInformationService.java
> +                    .filter(eReference -> containedObjectEClass.equals(eReference.getEReferenceType()))
ajouter `|| containedObjectEClass.getEAllSuperTypes().stream()
                        .anyMatch(superType -> superType.equals(eReference.getEReferenceType())`

2025-01-24 10:43 UTC, gcoutable submitted a review, later dismissed

2025-01-24 10:43 UTC, gcoutable commented on CHANGELOG.adoc
> +- https://github.com/eclipse-sirius/sirius-web/issues/3740[#3740] [sirius-web] Add support for object duplication from explorer
Add one or many images

2025-01-24 10:43 UTC, gcoutable commented on packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/KeyboardShortcut.tsx
> +export const KeyboardShortcut = ({ editingContextId, readOnly, children }: KeyboardShortcutProps) => {
It's a very generic name for a very specific behavior.
With this kind of name I would think this component could be reuse to define any shortcut do perform any action.
Here it is just  [CMD+d] for duplication.
So, either you change the name for something more specific, either you make the implementation more generic.

2025-01-24 10:43 UTC, gcoutable commented on packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/KeyboardShortcut.tsx
> +export const KeyboardShortcut = ({ editingContextId, readOnly, children }: KeyboardShortcutProps) => {
It's a very generic name for a very specific behavior.
With this kind of name I would think this component could be reuse to define any shortcut do perform any action.
Here it is just  [CMD+d] for duplication.
So, either you change the name for something more specific, either you make the implementation more generic.

2025-01-24 10:43 UTC, gcoutable commented on packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx
> +              <KeyboardShortcut editingContextId={context.project.currentEditingContext.id} readOnly={readOnly}>
Looking at the name of this component, I would think it has been put to deep in the DOM tree.
Looking at the implementation, I would think it should be around the explorer only.
Is it possible to only wrap the explorer instead of the whole workbench?
Is it a matter of where the focus is?

2025-01-24 10:43 UTC, gcoutable commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/useContainmentFeatureNames.ts
> +  let containmentFeatureNames = null;
`containmentFeatureNames` should not be initialized with `null` or, accept `null` values in `UseContainmentFeatureNamesValue`

2025-01-25 09:59 UTC, sbegaudeau requested changes

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx
> +              <KeyboardShortcut editingContextId={context.project.currentEditingContext.id} readOnly={readOnly}>
I couldn't agree more, this should be included only within the explorer and axtive only when the explorer is focused (there should probably be an indicator of the focus on a view to understand that...

2025-01-25 09:59 UTC, sbegaudeau commented on packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/utils/SiriusEMFCopier.java
> +                        if (eStructuralFeature instanceof EAttribute) {
this can be only one if

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/DuplicateDialogTreeEventInput.java
> +package org.eclipse.sirius.web.application.object;
I think that there's an issue of responsibility in this contribution. This is a feature for the explorer. I don't see why there should be barely any change outside of:

- `org.eclipse.sirius.web.application.views.explorer` on the backend
- `packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/explorer`

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/dto/DuplicateObjectInput.java
> +public record DuplicateObjectInput(@NotNull UUID id, @NotNull String editingContextId, @NotNull String objectId, @NotNull String containerId, @NotNull String containmentFeatureName,
Could you put each parameter on a specific line to make it more readable please

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/DuplicateObjectEventHandler.java
> +            result = new Failure(MessageFormat.format("The object with id \"{0}\" does not exist", objectToDuplicateId));
Use the message service instead (I think we already have a message in case something does not exist)

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/DuplicateObjectEventHandler.java
> +        IStatus result = new Failure("The duplication of the object has failed");
Use the message service

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectModal.tsx
> +  }, [containmentFeatureNames]);
Why is the result of the query stored in a state?

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectModal.tsx
> +    if (selection.entries[0]?.kind !== 'siriusWeb://document')
Do not use kind, we are trying to remove it

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectModal.tsx
> +  const treeId: string = `modelBrowser://container?ownerKind=${encodeURIComponent(
AHAH! There it is! Could you explain me why this feature of the explorer is based on reference widget with this tiny but critical coupling to `modelbrower://`? Preventing coupling is our number one priority.

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectModal.tsx
> +            disabled={!state.containmentFeatureName}
Use the loading state that should be provided by the useDuplicateObject modal to disable the dialog while the operation is being performed.

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/objects/ObjectDuplicationControllerIntegrationTests.java
> +    @Sql(scripts = {"/scripts/cleanup.sql"}, executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD, config = @SqlConfig(transactionMode = SqlConfig.TransactionMode.ISOLATED))
`@GivenSiriusWebServer`

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/objects/ObjectDuplicationControllerIntegrationTests.java
> +    @Sql(scripts = {"/scripts/cleanup.sql"}, executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD, config = @SqlConfig(transactionMode = SqlConfig.TransactionMode.ISOLATED))
`@GivenSiriusWebServer`

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/resources/schema/duplicateobject.graphqls
> +  containmentFeatureNames(containerId: ID!, containedObjectId: ID!): EditingContextContainmentFeatureNamesPayload!
Inputs and payloads are to be used in the GraphQL schema only for mutations, just return the list of string directly:

```
extend type EditingContext {
  containmentFeatureNames(containerId: ID!, containedObjectId: ID!): [String!]!
}
```

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/resources/schema/duplicateobject.graphqls
> +union EditingContextContainmentFeatureNamesPayload = ErrorPayload | EditingContextContainmentFeatureNamesSuccessPayload
To be removed

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/dto/EditingContextContainmentFeatureNamesSuccessPayload.java
> +}
Queries do not return payloads

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/useContainmentFeatureNames.ts
> +          }
To be updated along with the type

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectModal.tsx
> +  }, [state.containerSelection, objectToDuplicateId]);
You don't need this to be based on useLazyQuery, you just need to expose skip as a property in `useContainmentFeatureNames`

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/useContainmentFeatureNames.ts
> +export const useContainmentFeatureNames = (): UseContainmentFeatureNamesValue => {
Add a `skip: boolean` parameter here and you can simplify the whole lifecycle

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectModal.types.ts
> +  onObjectDuplicated: (object: Selection) => void;
selection: Selection

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectModal.tsx
> +      onObjectDuplicated({ entries: [duplicatedObject] });
DuplicatedObject has more properties than what is expected in the selection entry object. Please just copy what's necessary

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/DuplicateDialogTreeEventInput.java
> +package org.eclipse.sirius.web.application.object;
Unless I'm missing something, I don't see much code related to the new representation for the content of the duplicate dialog... I would have expected an amount of code comparable to the selection dialog for example. Where is the EventProcessorFactory ? The RepresentationMetadataProvider ? The Subscription data fetcher ?The event input ? The GraphQL schema ?

I feel like there should be something in `org.eclipse.sirius.web.application.views.explorer.dialogs.duplicateobject` like:

- `org.eclipse.sirius.web.application.views.explorer.dialogs.duplicateobject.controllers.SubscriptionDuplicateObjectDialogTreeEventDataFetcher`
- `org.eclipse.sirius.web.application.views.explorer.dialogs.duplicateobject.services.DuplicateObjectDialogEventProcessorFactory`

I am missing quick a lot of classes for something that should be working given that there are Cypress tests that seems to show that it works.

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/useDuplicateDialogTreeSubscription.ts
> +export const useDuplicateDialogTreeSubscription = (
`useDuplicateDialogSubscription` is enough

2025-01-25 09:59 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectModal.tsx
> +  const treeId: string = `modelBrowser://container?ownerKind=${encodeURIComponent(
I'm not technically against the model browser becoming something generic but I am missing a first PR to extract the model browser out of the reference widget in some dedicated modules backend and frontend like the selection dialog.

And we would have to remove anything specific from the reference widget out of the model browser.

2025-01-28 12:37 UTC, frouene commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/DuplicateObjectEventHandler.java
> +        IStatus result = new Failure("The duplication of the object has failed");
If I do that, I'll have to put it directly in `sirius-web-application`, do we want to add a MessageService in `sirius-web-application`?

2025-01-31 16:07 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/DuplicateObjectEventHandler.java
> +        IStatus result = new Failure("The duplication of the object has failed");
Why? There's tons of code in `sirius-web-application` using the message service. You can either use an existing generic message or create your own specific message, you choose.

2025-01-31 16:42 UTC, frouene commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/DuplicateObjectEventHandler.java
> +        IStatus result = new Failure("The duplication of the object has failed");
Done

2025-02-01 09:54 UTC, sbegaudeau requested changes

2025-02-01 09:54 UTC, sbegaudeau commented on packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/messages/ICollaborativeMessageService.java
> +    String objectDuplicationFailed();
Why are you modifying the collaborative message service?

2025-02-01 09:54 UTC, sbegaudeau commented on packages/core/backend/sirius-components-collaborative/src/main/resources/messages/sirius-web-spring-collaborative.properties
> +OBJECT_DOES_NOT_EXIST=The object with id "{0}" does not exist
This does not have to be changed

2025-02-01 09:54 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/dialogs/duplicateobject/services/DuplicateObjectDialogTreeDescriptionProvider.java
> +                // model browser in the list of representations that can be created. Thus, we will return false all the time.
Is there a point in duplicating the model browser? Why pick this approach. As I said, I would have expected a first PR to extract the model browser instead of just copying and pasting half a dozen files. Unless there is a point that I'm missing?

2025-02-28 15:40 UTC, sbegaudeau requested changes
- There are still unnecessary changes in message services and irrelevant message services used
- The kind is still used at multiple locations
- The label of the duplicated object is not propagated to the selection anymore but it is still requested

2025-02-28 15:40 UTC, sbegaudeau commented on packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/messages/CollaborativeMessageService.java
> +    @Override
Nothing in `sirius-components-collaborative` uses this new message, I suspect that it does not belong there.

2025-02-28 15:40 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/dto/DuplicateObjectInput.java
> +public record DuplicateObjectInput(@NotNull UUID id,
formatting

2025-02-28 15:40 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/DuplicateObjectEventHandler.java
> +    private final IMessageService messageService;
This does not make any sense to use not one, not two but three message services O___ô

2025-02-28 15:40 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/resources/schema/duplicateobject.graphqls
> +  object: Object
Why would that be optional? If the copy is a success, how could we not find this object?

2025-02-28 15:40 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-tests/src/main/java/org/eclipse/sirius/web/tests/graphql/ContainmentFeatureNamesQueryRunner.java
> +    private static final String DOMAINS_QUERY = """
`DOMAINS_QUERY`?

2025-02-28 15:40 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/objects/ObjectDuplicationControllerIntegrationTests.java
> +        assertThat(objectKind).isEqualTo("siriusComponents://semantic?domain=domain&entity=Entity");
Don't rely on kind

2025-02-28 15:40 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/objects/ObjectDuplicationControllerIntegrationTests.java
> +
Don't really on kind

2025-02-28 15:40 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectKeyboardShortcut.tsx
> +      }
Do not rely on kind

2025-02-28 15:40 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectKeyboardShortcut.tsx
> +          objectToDuplicateKind={selection.entries[0].kind}
Do not rely on kind

2025-02-28 15:40 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectModal.tsx
> +              ownerId={''}
`=""`, no need to interpret an expression for a static string (same comment a couple times below)

2025-02-28 15:40 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/useDuplicateObject.types.ts
> +  label: string;
Do you really need the label?

2025-02-28 15:40 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/useContainmentFeatureNames.ts
> +    containerId,
The expected value here cannot be null

2025-02-28 16:20 UTC, frouene commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectKeyboardShortcut.tsx
> +      }
How can I apply duplication only to the element sementic without the kind?
For information, this is how we filter menus in explorer (https://github.com/eclipse-sirius/sirius-web/blob/5cf8aa642b5cc5761bf3d58056352d2afede0a7b/packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/ObjectTreeItemContextMenuContribution.tsx#L35)

2025-03-03 14:37 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectKeyboardShortcut.tsx
> +      }
The link in question is using `GQLTreeItem#kind`, you are using `SelectionEntry#kind`. While `GQLTreeItem#kind` will need to be removed at some point in time, this is a different issue. I need to get rid of `SelectionEntry#kind` sooner rather than later so I don't want more code creating coupling with this.

2025-03-05 09:09 UTC, frouene commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectKeyboardShortcut.tsx
> +      }
Doing without `kind` implies more complex changes, so as a first step I removed the shortcut from this PR.
This will be addressed in a separate PR

2025-03-11 16:38 UTC, frouene commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectKeyboardShortcut.tsx
> +      }
Thanks to https://github.com/eclipse-sirius/sirius-web/commit/845c6e8a3386f91eee884c6fd988b289ed9849ca
I reintroduced the shortcut without using kind on selection

2025-03-13 16:02 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/useDuplicateObject.ts
> +          kind
This can be removed I believe

2025-03-13 16:02 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/useDuplicateObject.types.ts
> +  kind: string;
Same comment

2025-03-13 16:03 UTC, sbegaudeau commented on packages/sirius-web/frontend/sirius-web-application/src/modals/duplicate-object/DuplicateObjectModal.tsx
> +      onObjectDuplicated({ entries: [{ id: duplicatedObject.id, kind: duplicatedObject.kind }] });
Kind can now be removed here too

2025-03-14 07:38 UTC, lfasani commented
A question about this functionality : will it be possible to duplicate from a resource into another resource (of the same project)?

2025-03-14 09:33 UTC, sbegaudeau commented
> A question about this functionality : will it be possible to duplicate from a resource into another resource (of the same project)?

https://www.youtube.com/watch?v=BJ0FR1MPm7o

2025-03-14 10:03 UTC, sbegaudeau approved these changes

2025-03-14 10:04 UTC, merged