[3763] Split the SelectionDialogDescription to prepare the Tree support
eclipse-sirius/sirius-web pull request #3857
Opened 2024-08-12 20:04 UTC by florianbarbin

The SelectionDialogDescription will now just hold the message information
The SelectionDialogDescription will now have a
selectionDialogTreeDescription to make it possible for the specifier to display the selectable elements as a tree.
The selectionDialogTreeDescription will be relatively simple at first time.

Bug: #3763

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?

The current SelectionDialog behavior is still the same.

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2024-08-20 07:50 UTC, AxelRICHARD commented on acceleoGeneratorSample.patch
What's this new file?

2024-08-20 07:50 UTC, AxelRICHARD commented on packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties
Please let the file as it was or double check that only your new entries have been added and the existing ones have not been modified.

2024-08-20 07:53 UTC, florianbarbin commented on acceleoGeneratorSample.patch
oups it should not be here

2024-08-20 07:53 UTC, florianbarbin commented on packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties
ok

2024-08-26 09:22 UTC, sbegaudeau requested changes
Most of the code looks good, I'll rebase it and fix the tiny issues detected here and there (it should mostly be conflicts with master)

2024-08-26 09:22 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/SelectionDialogDescriptionSelectionCandidatesExpressionMigrationParticipant.java
> +    private static final String PARTICIPANT_VERSION = "2024.9.0-202408121400";
Note to myself or whoever ends up merging this PR: this will have to be updated before the final merge

2024-08-26 09:22 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/ModelOperationDiagramDescriptionProvider.java
> +
I'll remove this empty line

2024-08-26 09:22 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/SelectionDialogTreeDescriptionBuilder.java
> +public class SelectionDialogTreeDescriptionBuilder {
This code should be regenerated after a rebase since the generation strategy has been modified. This file will thus end up in another package.

2024-08-26 09:22 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/diagram/DiagramBuilders.java
> +    /**
Same comment as the one before

2024-08-26 09:22 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/diagram/SelectionDialogDescriptionBuilder.java
> +    public SelectionDialogDescriptionBuilder selectionMessage(java.lang.String value) {
Same comment

2024-08-26 09:22 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/diagram/SelectionDialogTreeDescriptionBuilder.java
> +public class SelectionDialogTreeDescriptionBuilder {
Same comment

2024-08-26 09:22 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/DiagramEditPlugin.java
> +            if ("png".equalsIgnoreCase(extension) || "gif".equalsIgnoreCase(extension) || "bmp".equalsIgnoreCase(extension) || "ico".equalsIgnoreCase(extension) || "jpg".equalsIgnoreCase(extension)
Formatting

2024-08-26 09:22 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/SelectionDialogDescriptionSelectionCandidatesExpressionMigrationParticipant.java
> +        if (eObject instanceof SelectionDialogDescription selectionDialogDescription) {
Can't we use a flatMap somewhere?

2024-08-26 09:24 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/diagram/DiagramBuilders.java
> +    /**
I was mistaken, it has already been rebased on top of the commit I was thinking about. There's nothing to change here

2024-08-26 09:24 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/SelectionDialogTreeDescriptionBuilder.java
> +public class SelectionDialogTreeDescriptionBuilder {
I was mistaken, it has already been rebased on top of the commit I was thinking about. There's nothing to change here

2024-08-26 09:24 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/diagram/SelectionDialogDescriptionBuilder.java
> +    public SelectionDialogDescriptionBuilder selectionMessage(java.lang.String value) {
I was mistaken, it has already been rebased on top of the commit I was thinking about. There's nothing to change here

2024-08-26 09:24 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-builder/src/main/java/org/eclipse/sirius/components/view/builder/generated/diagram/SelectionDialogTreeDescriptionBuilder.java
> +public class SelectionDialogTreeDescriptionBuilder {
I was mistaken, it has already been rebased on top of the commit I was thinking about. There's nothing to change here

2024-08-26 09:25 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/DiagramEditPlugin.java
> +            if ("png".equalsIgnoreCase(extension) || "gif".equalsIgnoreCase(extension) || "bmp".equalsIgnoreCase(extension) || "ico".equalsIgnoreCase(extension) || "jpg".equalsIgnoreCase(extension)
Done

2024-08-26 09:25 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/ModelOperationDiagramDescriptionProvider.java
> +
Done

2024-08-26 09:26 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/SelectionDialogDescriptionSelectionCandidatesExpressionMigrationParticipant.java
> +    private static final String PARTICIPANT_VERSION = "2024.9.0-202408121400";
Updated

2024-08-26 09:28 UTC, sbegaudeau commented
I'll wait for the build and merge it

2024-08-26 09:50 UTC, sbegaudeau approved these changes

2024-08-26 09:50 UTC, merged