[1062] Allow expand/collapse of tree items without selecting them
eclipse-sirius/sirius-web pull request #4084
Opened 2024-10-09 13:38 UTC by pcdavid

This was originally fixed in 2022.3.0 via commit
48913d175c88a80d0dc10fd16f51a149bcaeee58, but broken again in
2024.3.0.

This reverts "[3056] Expand the clickable/draggable zone for tree
items" (commit 190b91909afd65e678f736257fe65d1f1ca641e8) which caused
the regression.

Bug: https://github.com/eclipse-sirius/sirius-web/issues/1062
Signed-off-by: Pierre-Charles David <pierre-charles.david@obeo.fr>

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2024-10-09 15:55 UTC, pcdavid commented
I tried to have both behaviors, and a small UI improvement:
* expanding/collapsing an item from the arrow/chevron does *not* select it;
* when hovering on an item, the whole line is highlighted, witouth the blank gap on the left side of the arrow/chevron we had before;
* the whole line (except for the chrevron, see above) is clicable to select the item, not just the arrow/icon/label/menu part

https://github.com/user-attachments/assets/f73097e7-1015-41de-9328-dcc82b57799e

2024-10-28 08:21 UTC, sbegaudeau requested changes
Could you add a Cypress test to validate this because we had so many regressions regarding the selection with the explorer recently that I'd like not to have more regressions in the future.

2024-10-28 09:48 UTC, pcdavid commented
Just a rebase for now, to check I did not mess up the conflict resolution with the work on DnD.

2024-10-28 15:08 UTC, pcdavid commented
> Could you add a Cypress test to validate this because we had so many regressions regarding the selection with the explorer recently that I'd like not to have more regressions in the future.

Done.

2024-11-19 09:35 UTC, sbegaudeau submitted a review, later dismissed

2024-11-19 09:35 UTC, sbegaudeau commented on packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
> +            draggable={true}
The `={true}` can be removed

2024-11-19 09:35 UTC, sbegaudeau commented on packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemArrow.tsx
> +      event.stopPropagation();
It would be better to filter what is relevant where it is necessary. I suspect that the onClick in TreeItem is performing the selection, it should either be moved just like onDragStart etc or only consider the click as relevant if it has been done on the relevant element.

2024-11-19 09:35 UTC, sbegaudeau commented on packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
> +            onClick={onClick}
Do you need the onClick twice?

2024-11-19 10:13 UTC, pcdavid commented on packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
> +            draggable={true}
Done.

2024-11-19 13:16 UTC, pcdavid commented on packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemArrow.tsx
> +      event.stopPropagation();
Done (I think).

2024-12-11 13:47 UTC, mcharfadi approved these changes

2024-12-11 13:47 UTC, mcharfadi commented on packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItem.tsx
> +    paddingLeft: `${24 * (depth - 1)}px`,
This does not look good but most of the style is not using theme values, so I don't think it's a big issue right now.

2024-12-11 14:33 UTC, mcharfadi commented on packages/trees/frontend/sirius-components-trees/src/treeitems/TreeItemArrow.tsx
> +      event.stopPropagation();
I also think it's good, I'll approve the PR

2024-12-11 14:38 UTC, merged