pcd/fix/deselect collapsed items
eclipse-sirius/sirius-web pull request #4147
Opened 2024-10-29 14:23 UTC by pcdavid

- **[1062] Allow expand/collapse of tree items without selecting them**
- **[1062] Make the whole tree item hoverable/clickable but do not select when expanding/collapsing from the arrow/chevron**
- **[1062] Add Cypress tests**
- **[4059] Deselect descendants of collapsed tree items**

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2024-10-29 16:12 UTC, frouene approved these changes

2024-10-30 08:25 UTC, pcdavid commented
While it works, I'm worried about the potential performance impacts.
If we decide to merge this in this state (depending on the priority given to the issue), we should open a new one to look at this.

There are two potential issues that may cause slowdowns on large trees (but this would need to be confirmed by measuring):
1. The code has to walk potentially several times over the `GQLTree` to find items/descendants from their id.
2. When it finds items to deselect, currently the only API we have is the very coarse-grained `setSelection`, which triggers a re-render of the whole workbench. Performance issues related to selection changes are quite common, and I have some ideas I'd like to try but they're not yet completely clarified.

2024-12-13 15:58 UTC, frouene commented on packages/sirius-web/frontend/sirius-web-application/src/views/explorer/ExplorerView.tsx
> +
No modification on this file

2024-12-13 16:17 UTC, pcdavid commented on packages/sirius-web/frontend/sirius-web-application/src/views/explorer/ExplorerView.tsx
> +
Done.

2024-12-13 16:19 UTC, frouene commented
There is a change in behavior on the DnD
![collapse](https://github.com/user-attachments/assets/e2ce4b54-8676-4dc4-8b70-f9cc46df3bee)
Before, the target treeItem expands

2024-12-17 14:11 UTC, sbegaudeau requested changes
Are we sure that this is the behavior we want? Because if I collapse an element, I would expect that the only thing that happen is the element is collapsed. Not the details view switching to an empty state.

2024-12-17 14:25 UTC, mcharfadi commented
Here, the first time I collapse, the parent is selected
The second time, the child is still selected

https://github.com/user-attachments/assets/cfb36236-2b41-429c-b714-89db3080b6de

2025-08-29 09:07 UTC, pcdavid commented
#5405 should actually fix this issue differently. This one will be closed if/when #5405 is accepted and merged.

2025-09-23 08:52 UTC, pcdavid commented
Fixed in a different way by #5405.

2025-09-23 08:52 UTC, closed without merging