table representation
eclipse-sirius/sirius-web pull request #4170
Opened 2024-11-04 16:36 UTC by frouene

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2024-11-19 13:36 UTC, mcharfadi requested changes, later dismissed

2024-11-19 13:36 UTC, mcharfadi commented on packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/ProjectTableRepresentationDescriptionProvider.java
> +public class ProjectTableRepresentationDescriptionProvider implements IEditingContextRepresentationDescriptionProvider {
I'm having issues manipulating this table. Lots of error on the front end console and cells with a checkbox don't have the correct value.
I'll try to see what's happening precisely.

2024-11-19 14:35 UTC, sbegaudeau requested changes
I'll rebase and merge the PR

2024-11-19 14:35 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PackageTableRepresentationDescriptionProvider.java
> +                    EReference eReference = (EReference) eStructuralFeature;
Check the type before casting

2024-11-19 14:35 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PackageTableRepresentationDescriptionProvider.java
> +                if (eType instanceof EEnum) {
You can create the newly casted variable directly in the if block (the same comment could be applied at multiple locations in this file)

2024-11-19 14:35 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PackageTableRepresentationDescriptionProvider.java
> +                                continue;
Do not use this keyword, improve the loop instead. I don't know why but I feel like this keyword is only there to bypass the fact that check style may have an issue with such deeply nested structure. Split the code properly instead. There are way to many if / for in several methods of this class.

2024-11-19 14:35 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/ProjectTableRepresentationDescriptionProvider.java
> +                featureToDisplayName.put(eSF, this.getDisplayName(eObject, eSF));
please use meaningful variable names

2024-11-19 14:35 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/ProjectTableRepresentationDescriptionProvider.java
> +    private BiFunction<VariableManager, Object, IStatus> getNewCellValueHandler() {
The cyclomatic complexity of this function is way too high.

2024-11-19 14:35 UTC, sbegaudeau commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/TableCreationParameters.java
> +            tableCreationParameters.tragetObject = this.targetObject; // can be null;
- traget
- why can it be null?

2024-11-19 14:35 UTC, sbegaudeau commented on packages/tables/frontend/sirius-components-tables/src/TableRepresentation.tsx
> +  const { complete, table } = useTableSubscription(editingContextId, representationId);
Prefer returning the payload instead of the raw representation object. You will one day end up with multiple payloads and it will be an issue.

2024-11-19 14:35 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PackageTableRepresentationDescriptionProvider.java
> +                                continue;
So this code is copied / pasted from another piece of code and you are creating two new copies of it with the very same issues. ~350 lines of almost identical code copied three times without any common parts.

2024-11-19 14:35 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PackageTableRepresentationDescriptionProvider.java
> +            return this.objectService.getFullLabel(candidate);
Don't use full label, it should be deleted.

2024-11-19 14:35 UTC, sbegaudeau commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/TableCreationParameters.java
> +            tableCreationParameters.tragetObject = this.targetObject; // can be null;
Given the fact that it is only called by TableEventProcessorFactory after a check in an optional, I don't see how this could be `null`.

2024-11-19 15:51 UTC, sbegaudeau commented
We have investigated the frontend errors with @mcharfadi and due to the way the description behaves it created a lot of duplicated targetObjectId for the columns since the name of a feature is not unique in a metamodel. As a result, we had thousands of errors on the frontend side (~20k in my first tests). I've fixed it in the updated commit but the end result is still not usable.

Even a basic checkbox does not work at all while trying to edit it. I'll see why and fix those convoluted hooks at the same time.

2024-11-19 15:53 UTC, sbegaudeau commented
Is it normal that I can enter some text content in a checkbox??? There's really something very odd on the frontend side.


https://github.com/user-attachments/assets/09f5ad8d-c9e2-4997-a1cc-20fc09fb20c0

2024-11-21 10:17 UTC, sbegaudeau approved these changes
I've completely reworked several parts of this pull request because it did not deliver anything that could pretend to work. There were tons of issues in the original PR but it was difficult to test for real at the time (since it could only work with a programmatic form) that I decided to merge the first version [based on a promise that it worked](https://github.com/eclipse-sirius/sirius-web/pull/4047#issuecomment-2441503744) but it does not.

I was not fan of the frontend and [its logic based on this `editedLines` state](https://github.com/eclipse-sirius/sirius-web/pull/4047#discussion_r1818701715) and after a careful debugging session using this PR it appears that it "works" in a way that is completely against the expected behavior of Sirius Web. It attempted to [modify the previously received state of the table](https://github.com/eclipse-sirius/sirius-web/blob/c8a779d2255159cb40c795b84c71231fb4681e9d/packages/tables/frontend/sirius-components-tables/src/useEditableCheckboxCell.tsx#L77) while simultaneously asking the server for the new state. Since Sirius Web is highly dynamic, just like Sirius Desktop, this does not make sense since we cannot know the impact of an edition on the frontend. I suspect that it was done mainly in order to try to support some sort of local edition on top of the textfield API of Material React Table. This is why it was easy to transform checkboxes into textfield since both concepts were [somehow connected](https://github.com/eclipse-sirius/sirius-web/blob/c8a779d2255159cb40c795b84c71231fb4681e9d/packages/tables/frontend/sirius-components-tables/src/TableContent.tsx#L123).

The support for checkboxes could not work given the fact that its code was just a quick copy / paste version of the textfield support (relying on OnBlur instead of OnChange event). It did not send any HTTP request to the backend when clicked.

In this PR, the support for select and multi select did not work either since, among other issues, the frontend was expecting to receive [the identifier of the current value](https://github.com/eclipse-sirius/sirius-web/blob/c8a779d2255159cb40c795b84c71231fb4681e9d/packages/tables/frontend/sirius-components-tables/src/useEditableMultiSelectCell.tsx#L87) and the backend was sending the label of the current value.

I have also taken this opportunity to rework the organization of the code which had tons of copied code in which some small differences created bugs. Now, several key parts of the table support are clearly visible. As an example, when the support for the view DSL will start to be introduce, several parts of the code in the table representation of Papaya will probably end up there (things like ColumnTargetObjectIdProvider, CellNewValueHandler, etc).

Now, it works even if the performances are not acceptable but we are working on that.

2024-11-21 10:42 UTC, merged