[4335] Add support of column reordering in table representation
eclipse-sirius/sirius-web pull request #4340
Opened 2024-12-20 16:46 UTC by jerome-obeo

Bug: https://github.com/eclipse-sirius/sirius-web/issues/4335

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2024-12-22 10:13 UTC, sbegaudeau commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls
> +  index: Int
Why such an index and why would it be optional? The order of the column is already given by the order in `Table#columns`, why would we need a second piece of information for that?

2024-12-23 08:32 UTC, jerome-obeo commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls
> +  index: Int
MRT handles column order separately from the column definition, so following this separation made more sense. Without any specific order information, the column order is given by column definition but as soon as the user decides to change this definition order, his order takes priority.

2025-01-02 15:34 UTC, sbegaudeau requested changes

2025-01-02 15:34 UTC, sbegaudeau commented on packages/tables/frontend/sirius-components-tables/src/table/TableContent.tsx
> +      enableColumnOrdering: true,
Why would this be enabled when the option to `enableColumnOrdering` received as a prop could be false?

2025-01-02 15:34 UTC, sbegaudeau commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls
> +  index: Int
Yes that's exactly my point, why are you both managing the state of the order of the columns on the frontend and the backend and reconciling both? I don't see the need for a duplicate column order state. Just tell the backend what to do once a column is dropped.

As it stand today, the state gets instantaneously updated on the frontend because you are considering that your code KNOWS what the consequence of this change in the order of the column will be and it gets synchronized later with the backend. The frontend should NEVER make any hypothesis on the consequences of a change. Let's consider that we have three columns, "A", "B" and "C", just because a column "B" is now dropped before a column "A", it does not mean that we will have "B", "A", "C" after the next refresh.

The frontend should just ask the backend to do its job.

2025-01-09 08:37 UTC, jerome-obeo commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls
> +  index: Int
Done, the index is no longer passed to the front end

2025-01-09 08:37 UTC, jerome-obeo commented on packages/tables/frontend/sirius-components-tables/src/table/TableContent.tsx
> +      enableColumnOrdering: true,
done

2025-01-13 13:03 UTC, sbegaudeau commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls
> +  index: Int
But you are still keeping the state of the order of the coumns in two location in the frontend in `useTableColumnOrdering` and in the backend in `Table#columns`?

2025-01-13 13:16 UTC, jerome-obeo commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls
> +  index: Int
I planned to remove the order from the front end and leverage the column order given by the back, but MRT does not allow us to be notified of changes in column order without having a React state that specifies the order of columns in the table global state.

2025-01-21 14:03 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/PapayaTableColumnControllerIntegrationTests.java
> +    @Sql(scripts = {"/scripts/cleanup.sql"}, executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD, config = @SqlConfig(transactionMode = SqlConfig.TransactionMode.ISOLATED))
This will have to be updated to use `@GivenSiriusWebServer` instead

2025-01-21 14:03 UTC, sbegaudeau commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/handlers/ReorderTableColumnsEventHandler.java
> +        this.messageService = messageService;
requireNonNull

2025-01-21 14:03 UTC, sbegaudeau commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls
> +  index: Int
The current approach does not work, the lifecycle is a complete mess. Just take two seconds to open a simple table and you will see that half a dozen requests are being made to the backend while not a single thing has been touched. With this contribution, at least to requests are sent to reorder columns while nobody has touched anything.

Here is an example with 1.5s of requests back and forth with the server for nothing: https://www.youtube.com/watch?v=ZIG8qN4H664

2025-01-21 14:25 UTC, sbegaudeau commented on packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/components/ColumnComponent.java
> +        columnVariableManager.put("columnIndex", columnIndex);
Just a sidenote, the index given to everybody is not the right index anymore since it gets changed later down.

2025-01-21 15:34 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/tables/PapayaTableColumnControllerIntegrationTests.java
> +    @Sql(scripts = {"/scripts/cleanup.sql"}, executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD, config = @SqlConfig(transactionMode = SqlConfig.TransactionMode.ISOLATED))
Done

2025-01-21 15:34 UTC, sbegaudeau commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/handlers/ReorderTableColumnsEventHandler.java
> +        this.messageService = messageService;
Done

2025-01-21 15:43 UTC, sbegaudeau commented
I've removed the local state and ensure that the requests that are not relevant are not sent to the backend anymore. There's still an issue with the columnIndex variable given to specifier which does not reflect the real state of the index. I'll wait for the build and merge it.

2025-01-21 15:44 UTC, sbegaudeau commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls
> +  index: Int
I've fixed it and remove the local state

2025-01-21 16:02 UTC, sbegaudeau approved these changes

2025-01-21 16:02 UTC, merged