[4343] Keep filters when opening a table
eclipse-sirius/sirius-web pull request #4344
Opened 2024-12-23 09:31 UTC by frouene

Bug: https://github.com/eclipse-sirius/sirius-web/issues/4343

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2025-01-03 08:52 UTC, sbegaudeau requested changes

2025-01-03 08:52 UTC, sbegaudeau commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/TableEventProcessorFactory.java
> +        String globalFilter = null;
I don't understand why `TableCreationParameters.Builder#globalFilter` or `TableCreationParameters.Builder#columnFilters` has to be nullable nor why it has to be nullable in `org.eclipse.sirius.components.tables.components.TableComponentProps`either and everywhere else for that matter and why you are trying to propagate even more `null` values everywhere.

You are doing this and deep down in `TableComponent`, you now have to do:

```
        var globalFilter = this.props.globalFilter();
        if (this.props.globalFilter() == null) {
            globalFilter = optionalPreviousTable.map(Table::getGlobalFilter).orElse("");
            variableManager.put(TableRenderer.GLOBAL_FILTER_DATA, globalFilter);
        }

        List<ColumnFilter> columnsFilters;
        if (this.props.columnFilters() == null) {
            columnsFilters = optionalPreviousTable.map(Table::getColumnFilters).orElse(List.of());
        } else {
            columnsFilters = this.props.columnFilters();
        }
```

Why aren't those values initialized properly in `TableEventProcessorFactory` given that you already have access to the previous version of the table? I don't see why more `null` solves anything given that you have to fallback to a proper value in the frontend

```
  const [globalFilter, setGlobalFilter] = useState<string>(table.globalFilter ?? '');

  useEffect(() => {
    if (enableGlobalFilter) {
      changeGlobalFilterValue(globalFilter ?? '');
      onGlobalFilterChange(globalFilter ?? '');
    }
  }, [globalFilter]);

  useEffect(() => {
    setGlobalFilter(table.globalFilter ?? '');
  }, [table.globalFilter]);
```

What state of the table is `null` supposed to represent?

2025-01-03 09:08 UTC, frouene commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/TableEventProcessorFactory.java
> +        String globalFilter = null;
When we open an existing table, we are unaware of the persisted value of the global filter on the front end (the same applies to the column filter). However, we do not want to send an empty value to the backend, as this would override the previous value (similar to when a user clicks the clear button in the filter section). Therefore, we need to recognize that we are in a situation where the table's global filter is not yet known, which is why I used the null value.

2025-01-03 09:08 UTC, frouene commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/TableEventProcessorFactory.java
> +        String globalFilter = null;
When we open an existing table, we are unaware of the persisted value of the global filter on the front end (the same applies to the column filter). However, we do not want to send an empty value to the backend, as this would override the previous value (similar to when a user clicks the clear button in the filter section). Therefore, we need to recognize that we are in a situation where the table's global filter is not yet known, which is why I used the null value.

2025-01-13 13:09 UTC, sbegaudeau commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/TableEventProcessorFactory.java
> +        String globalFilter = null;
I understand why the frontend can send a lack of value to the back in the URL of the subscription sure but here we are opening the representation and we have the table from the database so we both know that:

- The frontend can't really send a meaningful value
- The source of truth is what has been persisted in the backend the last time

So why give `null` to everybody if the real answer is just next to us? Am I mistaken in thinking that the only possible value here is the real value coming the previous table loaded line 88?

2025-01-13 15:40 UTC, frouene commented on packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/TableEventProcessorFactory.java
> +        String globalFilter = null;
Yes, you're right, I didn't understand your comment at first. I can indeed directly retrieve the persisted value without needing to handle the null case.
I've updated the PR to remove all nulls for globalSearch and columnFilter

2025-01-14 14:09 UTC, sbegaudeau approved these changes
I'll merge it after the build

2025-01-14 14:26 UTC, merged