[4348] Move quick tools declaration on the backend
eclipse-sirius/sirius-web pull request #4349
Opened 2024-12-27 09:02 UTC by mcharfadi

Bug: https://github.com/eclipse-sirius/sirius-web/issues/4348

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2025-02-04 10:46 UTC, sbegaudeau requested changes

2025-02-04 10:46 UTC, sbegaudeau commented on packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/api/DiagramImageConstants.java
> +    public static final String HIDE_SVG = "/icons/full/obj16/HideTool.svg";
Where is this image coming from? Do not add coupling between unrelated modules. Is that coming from the diagram view DSL? If so, `sirius-components-collaborative-diagrams` can be reused with the view DSL so it cannot be referenced this way. Since I don't see any reference to this constant anywhere in `sirius-components-collaborative-diagrams`, you can remove it entirely

2025-02-04 10:46 UTC, sbegaudeau commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/collapse/useCollapseExpandElement.tsx
> +    async (nodeId: string, collapsingState: GQLCollapsingState) => {
Do not use async not await

2025-02-04 10:46 UTC, sbegaudeau commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/collapse/useCollapseExpandElement.tsx
> +      }
Just write this kind of code as we always do

2025-02-04 10:46 UTC, sbegaudeau commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/delete/useDiagramDeleteMutation.tsx
> +export const useDiagramDeleteMutation = (): UseDiagramDeleteMutation => {
This hook should probably be named `useDeleteFromDiagram` to stay consistent with our naming conventions

2025-02-04 10:46 UTC, sbegaudeau commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/delete/useDiagramDeleteMutation.tsx
> +  );
Don't use async / await, we have tons of hooks using mutations, just do the same thing

2025-02-04 10:46 UTC, sbegaudeau commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tools/useSingleClickOnDiagramElementTool.tsx
> +        const { data } = await invokeSingleClickOnDiagramElementTool({
Don't use async / await

2025-02-04 10:46 UTC, sbegaudeau commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tools/useSingleClickOnDiagramElementTool.tsx
> +    async (tool: GQLTool, variables: GQLToolVariable[]) => {
Don't use async / await

2025-02-04 10:46 UTC, sbegaudeau commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tools/useInvokeTool.tsx
> +  const { hideDiagramElementPalette } = useDiagramElementPalette();
Is that a good idea to create some coupling between all these concepts?

2025-02-04 11:09 UTC, mcharfadi commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/collapse/useCollapseExpandElement.tsx
> +    async (nodeId: string, collapsingState: GQLCollapsingState) => {
Yes it was already used so I did not change it but if there was no reason to use async I can remove it.

2025-02-04 11:27 UTC, mcharfadi commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tools/useInvokeTool.tsx
> +  const { hideDiagramElementPalette } = useDiagramElementPalette();
It seems to me that the coupling was already there in `usePalette`.

With this PR, we start to have a hook per mutation that only do the mutation, so it can be reused anywhere and even could be exported later on.

I think we could still reduce the coupling between `useInvokeTool` and `usePalette`.

The palette should probably call `usePalette `in order to only execute the query and `useInvokeTool` to get only `handleToolClick ` would that be be better ? That would allow us to reuse `useInvokeTool` too.

Theses changes are helpful to reduce the complexity of the code and later on merge all palettes into one so we don't have the palette in the nodes and in order to simplify the states related to the palette.

2025-09-19 12:59 UTC, mcharfadi commented on packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/api/DiagramImageConstants.java
> +    public static final String HIDE_SVG = "/icons/full/obj16/HideTool.svg";
I downloaded icons from [fonts.google](https://fonts.google.com/icons) and I placed them in `/sirius-components-collaborative-diagrams/src/main/resources/diagram-images/adjust.svg`

2025-09-19 12:59 UTC, mcharfadi commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/collapse/useCollapseExpandElement.tsx
> +    async (nodeId: string, collapsingState: GQLCollapsingState) => {
done

2025-09-19 12:59 UTC, mcharfadi commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/collapse/useCollapseExpandElement.tsx
> +      }
done

2025-09-19 13:00 UTC, mcharfadi commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/delete/useDiagramDeleteMutation.tsx
> +export const useDiagramDeleteMutation = (): UseDiagramDeleteMutation => {
This was modified in a previous commit

2025-09-19 13:00 UTC, mcharfadi commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/delete/useDiagramDeleteMutation.tsx
> +  );
done

2025-09-19 13:00 UTC, mcharfadi commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tools/useSingleClickOnDiagramElementTool.tsx
> +        const { data } = await invokeSingleClickOnDiagramElementTool({
done

2025-09-19 13:00 UTC, mcharfadi commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tools/useSingleClickOnDiagramElementTool.tsx
> +    async (tool: GQLTool, variables: GQLToolVariable[]) => {
done

2025-09-19 13:04 UTC, mcharfadi commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tools/useInvokeTool.tsx
> +  const { hideDiagramElementPalette } = useDiagramElementPalette();
So, I kept the custom hooks here.
I'm not sure how to reduce coupling even more.

Still, it will allow us to move the `PaletteQuickAccessToolBar ` in the palette package (after modifying the `diagramPaletteToolExtensionPoint `that is still coupled with XYFlow types)

2025-10-20 13:32 UTC, mcharfadi commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tools/useInvokeTool.tsx
> +  const { hideDiagramElementPalette } = useDiagramElementPalette();
Note that if we move forward with this PR https://github.com/eclipse-sirius/sirius-web/pull/5685

Then we could implement a `toolHandler `for these `quicktools `and remove these specific mutations.
They would behave like a SingleClickOnDiagramElementTool

2025-11-07 15:24 UTC, sbegaudeau requested changes

2025-11-07 15:24 UTC, sbegaudeau commented on packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/api/DiagramImageConstants.java
> +
What are those? What is swipe right supposed to be as an icon? I need meaningful icon names relevant to their goal, not their appearance. And that's also relevant for the name of the files

2025-11-07 15:24 UTC, sbegaudeau commented on packages/diagrams/frontend/sirius-components-diagrams/src/renderer/handles/useHandlesLayout.tsx
> +    (edgeId: string): void => {
What's the point in this PR? Just like any handle-related changes...

2025-11-07 15:24 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                .label("Adjust size")
Use the internationalization APIs for that

2025-11-07 15:24 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                .label("Reset-outside-label-position")
Same comment (and why the dashes?)

2025-11-07 15:24 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                .label("Reset bending points")
Same comment

2025-11-07 15:24 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                .label("Reset Handles Position")
Same comment

2025-11-07 15:24 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                        .label("Collapse")
Same comment

2025-11-07 15:24 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                        .label("Expand")
Same comment

2025-11-07 15:24 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +        String label = "Fade element";
Same comment

2025-11-07 15:24 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +            label = "Unfade element";
Same comment

2025-11-07 15:24 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                    .label("Unpin")
Same comment

2025-11-07 15:24 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                    .label("Pin")
Same comment

2025-11-07 15:24 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +    public List<ITool> createQuickAccessTools(DiagramContext diagramContext, Object diagramElementDescription, Object diagramElement) {
What's the point of this method?

2025-11-07 15:30 UTC, mcharfadi commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                .label("Reset-outside-label-position")
What dashes ?

2025-11-07 15:32 UTC, mcharfadi commented on packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/api/DiagramImageConstants.java
> +
It's material icons https://fonts.google.com/icons
I can change the names

2025-12-03 09:33 UTC, mcharfadi commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +    public List<ITool> createQuickAccessTools(DiagramContext diagramContext, Object diagramElementDescription, Object diagramElement) {
Some tools are declared as quicktools and also in the edit sections

2025-12-03 09:33 UTC, mcharfadi commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                    .label("Pin")
done

2025-12-03 09:33 UTC, mcharfadi commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                    .label("Unpin")
done

2025-12-03 09:33 UTC, mcharfadi commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +            label = "Unfade element";
done

2025-12-03 09:33 UTC, mcharfadi commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +        String label = "Fade element";
done

2025-12-03 09:33 UTC, mcharfadi commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                        .label("Expand")
done

2025-12-03 09:33 UTC, mcharfadi commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                        .label("Collapse")
done

2025-12-03 09:33 UTC, mcharfadi commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                .label("Reset Handles Position")
done

2025-12-03 09:33 UTC, mcharfadi commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                .label("Reset bending points")
done

2025-12-03 09:33 UTC, mcharfadi commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                .label("Reset-outside-label-position")
done

2025-12-03 09:33 UTC, mcharfadi commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +                .label("Adjust size")
done

2025-12-03 09:41 UTC, mcharfadi commented on packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/api/DiagramImageConstants.java
> +    public static final String HIDE_SVG = "/icons/full/obj16/HideTool.svg";
done

2025-12-03 09:42 UTC, mcharfadi commented on packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/api/DiagramImageConstants.java
> +
done

2025-12-12 15:45 UTC, sbegaudeau reviewed
I'll rebase this PR, perform a couple of tests and merge it

2025-12-12 15:45 UTC, sbegaudeau commented on packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/Node.java
> +    }
Why should this be done here?

2025-12-12 15:45 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/tools/ViewGroupPaletteProvider.java
> +            .toList();
Formatting, either you are manipulating the code manually or you seems to have multiple issues with your IDE (import order, formatting)

2025-12-12 15:45 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/tools/ViewGroupPaletteProvider.java
> +                .forEach(quickAccessTools::add);
Formatting

2025-12-12 15:45 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/PaletteDefaultToolsProvider.java
> +        }
missing `this.`

2025-12-12 15:45 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/resources/messages/sirius-components-view-emf_fr.properties
> +FADE=Estompés
This should be a verb not an adjective

2025-12-12 15:45 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/resources/messages/sirius-components-view-emf_fr.properties
> +HIDE=Caché
Same comment

2025-12-12 15:46 UTC, pcdavid commented on packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/Node.java
> +    }
Typo: isFadded => isFaded

2025-12-12 15:53 UTC, sbegaudeau commented on packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/Node.java
> +    }
This change in Node.java is only there for a test? I'll remove it. Use `DiagramAssertions#assertThat` to perform your assertions, it has several utility methods to replace things like this:

```
assertThat(siriusWebDomainNode.isPinned()).isTrue();
```

by

```
assertThat(siriusWebDomainNode).isPinned();
```

2025-12-12 15:59 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/tools/ViewGroupPaletteProvider.java
> +            .toList();
You can also dramatically simply this code, you can use flatmap and you don't need to case anything.

2025-12-12 16:00 UTC, sbegaudeau commented on packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/tools/ViewGroupPaletteProvider.java
> +                .forEach(quickAccessTools::add);
Don't use this pattern of creating an empty collection to add things to it, just use `toList()`

2025-12-12 19:36 UTC, sbegaudeau approved these changes

2025-12-12 19:36 UTC, merged