[4345] Make table cells independently selectable
eclipse-sirius/sirius-web pull request #4350
Opened 2024-12-30 09:11 UTC by frouene

Bug: https://github.com/eclipse-sirius/sirius-web/issues/4345

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2025-01-03 08:59 UTC, sbegaudeau requested changes
Most of the modified files are not related to the issue being treated

2025-01-03 08:59 UTC, sbegaudeau commented on packages/tables/frontend/sirius-components-tables/src/table/TableContent.types.ts
> +  enableCursorBasedPagination: boolean;
What is the point of this change? Not only it's not related to the issue being treated but I fail to see what value does it bring?

2025-01-03 08:59 UTC, sbegaudeau commented on packages/tables/frontend/sirius-components-tables/src/cells/Cell.tsx
> +}));
That's odd, why are you layouting things in the children instead of its parent?

2025-01-03 08:59 UTC, sbegaudeau commented on packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnFiltering.ts
> +      columnFilters: [],
Why this change?

2025-01-03 09:11 UTC, frouene commented
> Most of the modified files are not related to the issue being treated

Ok, I will move these changes to specific PR

2025-01-03 14:03 UTC, frouene commented on packages/tables/frontend/sirius-components-tables/src/columns/useTableColumnFiltering.ts
> +      columnFilters: [],
Move to a separate [PR](https://github.com/eclipse-sirius/sirius-web/pull/4363)

2025-01-03 14:04 UTC, frouene commented on packages/tables/frontend/sirius-components-tables/src/table/TableContent.types.ts
> +  enableCursorBasedPagination: boolean;
Move to a separate [PR](https://github.com/eclipse-sirius/sirius-web/pull/4361)

2025-01-03 15:00 UTC, frouene commented on packages/tables/frontend/sirius-components-tables/src/cells/Cell.tsx
> +}));
I've moved the behavior in the parent `useTableColumns`

2025-01-24 09:29 UTC, sbegaudeau commented on packages/tables/frontend/sirius-components-tables/src/table/TableContent.tsx
> +        <div
This should probably end up being extracted in a dedicated component, it should be soon anyway

2025-01-24 10:16 UTC, sbegaudeau approved these changes

2025-01-24 10:54 UTC, merged