[4352] Add support to range column filters in table
eclipse-sirius/sirius-web pull request #4353
Opened 2024-12-31 08:15 UTC by frouene

Bug: https://github.com/eclipse-sirius/sirius-web/issues/4352

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

## Review

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

2025-01-03 09:20 UTC, sbegaudeau requested changes

2025-01-03 09:20 UTC, sbegaudeau commented on packages/tables/backend/sirius-components-tables/pom.xml
> +		</dependency>
I have not reviewed the whole PR but a change to a pom.xml is always something important so I've only looked at this file.

`sirius-components-tables` like most very low level parts of Sirius Components should not have any dependency to anything unless it is absolutely critical. The job done with this code should not be the responsibility of this project. It is not the responsibility of `sirius-components-tables` to support the fact that the table range column filters are serialized over the network in this way.

2025-01-03 09:20 UTC, sbegaudeau commented on packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/URLParser.java
> +            var rawValue = value.substring(1, value.length() - 1);
Could you explain me what this change of behavior supposed to do? It's a bit complex to understand just from a Quick Look at the code, what is the difference in the old vs new behavior?

2025-01-03 09:29 UTC, frouene commented on packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/URLParser.java
> +            var rawValue = value.substring(1, value.length() - 1);
Since the filter values of a column can be a list, we end up with uri of this type `[467ec1c3-8ba7-32dc-9d72-71a2ccad161b:["0","1"],4752c1c3-8ba7-32dc-9d72-71a2ccad161b:["1","2"]]`
The previous implementation of `getParameterEntries` split each `,` whiche end up giving something like ` 467ec1c3-8ba7-32dc-9d72-71a2ccad161b:["0"` ,`"1"]` ...
In the new approach, I consider the level of `[` to only split the first list.

2025-01-16 13:55 UTC, frouene commented on packages/tables/backend/sirius-components-tables/pom.xml
> +		</dependency>
I removed this dependency, I propagate the serialized value up to the specifier predicate

2025-01-24 14:27 UTC, sbegaudeau approved these changes
I'll wait for the build and merge it

2025-01-24 14:27 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PackageTableRepresentationDescriptionProvider.java
> +        ObjectMapper objectMapper = new ObjectMapper();
Why not reuse the object mapper bean?

2025-01-24 14:27 UTC, sbegaudeau commented on packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/URLParser.java
> +            var rawValue = value.substring(1, value.length() - 1);
You could simply encode your value, that's how things tend to be in URLs to prevent conflicts with separators

2025-01-24 14:27 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PackageTableRepresentationDescriptionProvider.java
> +                    boolean isValidColumFilterCandidat = true;
All that should be extracted in a dedicated method to be readable

2025-01-24 14:27 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PackageTableRepresentationDescriptionProvider.java
> +                        } catch (JsonProcessingException ignored) {
Why so many exceptions ignored? We can log them and select which logger to display while executing the application.

2025-01-24 14:27 UTC, sbegaudeau commented on packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/PackageTableRepresentationDescriptionProvider.java
> +                .headerIconURLsProvider(variableManager -> List.of("/icons/svg/Default.svg"))
Don't depend on images from other projects

2025-01-24 14:27 UTC, sbegaudeau commented on packages/core/backend/sirius-components-core/src/main/java/org/eclipse/sirius/components/core/URLParser.java
> +            var rawValue = value.substring(1, value.length() - 1);
We will move forward with that but I'm not sure that we will keep this additional complexity only for table representations. We will see.

2025-01-24 15:19 UTC, merged