[559] Create new Selection Representation
eclipse-sirius/sirius-web pull request #80
Opened 2021-06-24 09:37 UTC by AxelRICHARD

Second commit of the 'support for a selection dialog on diagram tools'.

Add a test description in 'sirius-web-sample-application', allowing to test with graphiql that a user can subscribe to this kind of representation.

Bug: https://github.com/eclipse-sirius/sirius-components/issues/559
Signed-off-by: Axel RICHARD <axel.richard@obeo.fr>

2021-06-30 09:14 UTC, sbegaudeau requested changes

2021-07-01 10:25 UTC, AxelRICHARD commented on backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/SelectionDescriptionConfiguration.java
> +        @SuppressWarnings({ "unchecked", "rawtypes" })
This test class is temporary. It will be deleted when the backend will be connected to the frontend and the odesign conversion will handle the 'select model variable element', so I don't think it is necessary to fix those warnings.

2021-07-01 10:40 UTC, AxelRICHARD commented on backend/sirius-web-sample-application/src/main/java/org/eclipse/sirius/web/sample/configuration/SelectionDescriptionConfiguration.java
> +        @SuppressWarnings({ "unchecked", "rawtypes" })
The problem comes from ".objectsProvider(variableManager -> variableManager.get(VariableManager.SELF, EObject.class).map(eObject -> new ArrayList(eObject.eContents())).orElse(new ArrayList<>()))". This returns an ArrayList<EObject> but the objectProvider wants a List<Object>.

2021-07-21 19:21 UTC, sbegaudeau commented
As discussed with @AxelRICHARD, this PR can be closed since a proper example has now been contributed in Flow Designer.

2021-07-21 19:21 UTC, closed without merging