Fix some issues related to launching the sample application
eclipse-sirius/sirius-web pull request #9
Opened 2020-11-24 13:31 UTC by pcdavid

2020-11-30 08:41 UTC, sbegaudeau requested changes

2020-11-30 08:41 UTC, sbegaudeau commented on scripts/launch.sh
> +     --spring.liquibase.change-log=classpath:db/changelog/sirius-web.db.changelog.xml
I am pretty sure that `-D` environment variables should be defined before `-jar`. Are you sure that this script is working?

2020-11-30 15:45 UTC, pcdavid commented on scripts/launch.sh
> +     --spring.liquibase.change-log=classpath:db/changelog/sirius-web.db.changelog.xml
It shouldn't... but it does. Maybe some Spring Boot magic? I'll change it anyway.

2020-11-30 15:48 UTC, pcdavid commented on scripts/launch.sh
> +     --spring.liquibase.change-log=classpath:db/changelog/sirius-web.db.changelog.xml
Fixed by https://github.com/eclipse-sirius/sirius-web/pull/9/commits/a49d33ef3e63be946a10d887c6c4fe366b5a5a11.

2020-12-01 08:40 UTC, sbegaudeau approved these changes

2020-12-01 08:46 UTC, sbegaudeau commented on scripts/launch.sh
>       --spring.datasource.password=dbpwd \
Could you fix the previous commit instead of creating a new one? I could squash everything but we would lost some part of the history but I can't partially squash that.

2020-12-02 13:46 UTC, merged